/* Shared quest/progress logic. No browser dependency. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MoonCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const WORLD={minX:-82,maxX:82,minZ:-84,maxZ:76};
const REGIONS=[{id:'crater',name:'Тихий кратер',x:-55,z:-50},{id:'valley',name:'Кристальная долина',x:58,z:-30},{id:'research',name:'Южная обсерватория',x:35,z:55}];
const KEY='moonkatty-new-horizons-v02';
const POINTS={recorder:[-5,-2],cell1:[-15,0],cell2:[-14,-9],cell3:[13,-15],antenna:[0,-24],pod:[-5,-2],engineer:[4,0],tool1:[-17,-15],tool2:[12,-10],navigator:[7,-25],beacon1:[-20,-23],beacon2:[17,-25],beacon3:[2,-37],scout:[-13,-30],artifact:[-24,-39],base:[-5,-7],final:[-5,-7],supply:[3,7],workshop:[-12,-7],solar:[-5,-14],dock:[-1,-12]};
Object.assign(POINTS,{signalStart:[4,0],clueCrater:[-55,-55],clueValley:[58,-35],clueResearch:[35,50],vault:[40,52],blueprint:[40,52],blueprintReturn:[4,0]});
const SIGNAL_NOTES={clueValley:'Кристальная долина · Запись I: первая цифра — 7.',clueCrater:'Тихий кратер · Запись II: вторая цифра — 3.',clueResearch:'Южная обсерватория · Запись III: третья цифра — 2.'};
const resources=Array.from({length:22},(_,i)=>({id:'res'+i,type:i%2?'metal':'crystals',x:Math.sin(i*2.399)* (7+i*.8),z:Math.cos(i*2.399)*(7+i*.8)-10}));resources[0].x=1.8;resources[0].z=15.8;resources[2].x=-2.1;resources[2].z=12.5;
for(const area of REGIONS)for(let i=0;i<12;i++)resources.push({id:'res'+resources.length,type:i%2?'metal':'crystals',x:area.x+Math.sin(i*2.399)*(4+i*.65),z:area.z+Math.cos(i*2.399)*(4+i*.65)});
// Shared authored obstacles: rendering and movement use the same dimensions.
const FIELD={x:2,z:-37,inner:3.8,outer:6.6,height:2.2};
const BARRIERS=[{x:-15,z:4.4,w:9.2,d:.44,h:.72},{x:-15,z:-4.4,w:9.2,d:.44,h:.72},{x:-19.4,z:0,w:.44,d:8.8,h:.72},{x:-10.6,z:0,w:.44,d:8.8,h:.72},{x:-16.1,z:-4.4,w:5.6,d:1.1,h:1.7},{x:-11.5,z:-7.4,w:5.6,d:1.1,h:1.7},{x:-16.1,z:-12.6,w:5.6,d:1.1,h:1.7}];
function obstacleAt(ch,x,z,alt=0){if(ch===1)return BARRIERS.find(o=>alt<o.h+.12&&Math.abs(x-o.x)<o.w/2+.22&&Math.abs(z-o.z)<o.d/2+.22)||null;const d=Math.hypot(x-FIELD.x,z-FIELD.z);return d>FIELD.inner&&d<FIELD.outer&&alt<FIELD.height?FIELD:null;}
const BEACON_NOTES={beacon1:'Бирюзовый маяк: я начинаю путь, после меня — золотой.',beacon2:'Золотой маяк: я соединяю начало с белым маяком.',beacon3:'Белый маяк: мой сигнал завершает путь.'};
function signalStrength(channel,value){return Math.max(0,Math.round(100-Math.abs(Number(value)-[32,68,45][channel])*7));}
/* Save schema v4 (growth stage 1): daily login streak, social/referral flags, cloud-sync timestamp.
   v2/v3 saves have none of these fields and migrate to safe defaults; existing progress is untouched. */
const SAVE_VERSION=6,CREW_IDS=['geologist','engineer','navigator','scout','botanist','pilot','doctor','captain'],CINEMA_IDS=['intro','ch1','ch2','ch3','crystal'],SOCIAL_IDS=['youtube','tiktok','instagram','x'],BADGES=['watch7','channel','crew1','crew5'];
const DAY_RE=/^\d{4}-\d{2}-\d{2}$/;
function freshStreak(){return{day:'',count:0,run:0,best:0,total:0};}
function freshTeam(){return{levels:{},at:0,store:{crystals:0,metal:0},cap:0,friends:0,codes:[],fails:0,lockUntil:0,rankSeen:-1,welcomeAt:0};}
function freshGrowth(){return{refBy:'',channel:false,social:{},badges:[],seen:'',applied:[],shareDay:'',resetAt:0};}
function clampInt(v,lo,hi,d=0){return Number.isFinite(v)?Math.max(lo,Math.min(hi,Math.floor(v))):d;}
function migrateGrowth(raw,s){const st=raw.streak;if(st&&typeof st==='object'&&DAY_RE.test(st.day)){s.streak={day:st.day,count:clampInt(st.count,1,7,1),run:clampInt(st.run,1,100000,1),best:0,total:clampInt(st.total,1,100000,1)};s.streak.best=Math.max(s.streak.run,clampInt(st.best,0,100000));}
 const g=raw.growth;if(g&&typeof g==='object'){const out=s.growth;out.refBy=typeof g.refBy==='string'&&/^\d{1,15}$/.test(g.refBy)?g.refBy:'';out.channel=g.channel===true;
  for(const id of SOCIAL_IDS){const t=g.social?.[id];if(t&&typeof t==='object')out.social[id]={openedAt:clampInt(t.openedAt,0,9e15),claimed:t.claimed===true};}
  out.badges=Array.isArray(g.badges)?[...new Set(g.badges.filter(b=>BADGES.includes(b)))]:[];out.seen=DAY_RE.test(g.seen)?g.seen:'';out.shareDay=DAY_RE.test(g.shareDay)?g.shareDay:'';
  out.applied=Array.isArray(g.applied)?[...new Set(g.applied.filter(id=>typeof id==='string'&&/^[\w:.-]{1,80}$/.test(id)))].slice(-300):[];out.resetAt=clampInt(g.resetAt,0,9e15);}
 s.updatedAt=clampInt(raw.updatedAt,0,9e15);migrateCinema(raw,s);migrateTeam(raw,s);}
// v6: base crew (levels + station store), redeemed signal codes (hashes), friends count, last celebrated rank.
function migrateTeam(raw,s){const t=raw.team;if(!t||typeof t!=='object')return;const out=s.team;
 for(const id of CREW_IDS){const l=t.levels&&t.levels[id];if(Number.isInteger(l)&&l>0)out.levels[id]=Math.min(5,l);}
 out.at=clampInt(t.at,0,9e15);for(const r of['crystals','metal']){const v=Number(t.store&&t.store[r]);out.store[r]=Number.isFinite(v)?Math.max(0,Math.min(100000,v)):0;}
 out.cap=clampInt(t.cap,0,2);out.friends=clampInt(t.friends,0,100000);out.codes=Array.isArray(t.codes)?[...new Set(t.codes.filter(h=>typeof h==='string'&&/^[0-9a-f]{24}$/.test(h)))].slice(-500):[];
 out.fails=clampInt(t.fails,0,10);out.lockUntil=clampInt(t.lockUntil,0,9e15);out.rankSeen=clampInt(t.rankSeen,-1,10,-1);out.welcomeAt=clampInt(t.welcomeAt,0,9e15);}// v5: which cutscenes were already shown. Older saves: skip openers of chapters the player has already started; the intro still plays once.
function migrateCinema(raw,s){const c=raw.cinema;if(c&&typeof c==='object'&&Array.isArray(c.seen)){s.cinema.seen=[...new Set(c.seen.filter(id=>CINEMA_IDS.includes(id)))];return;}
 const seen=[];for(let ch=1;ch<s.chapter;ch++)seen.push('ch'+ch);if(s.chapter===1&&s.recorder||s.chapter===2&&s.engineerMet||s.chapter===3&&s.signalBriefed)seen.push('ch'+s.chapter);
 if(s.collected.some(id=>resources.find(r=>r.id===id)?.type==='crystals'))seen.push('crystal');s.cinema.seen=seen;}
const COST={habitat:[4,6],workshop:[2,3],solar:[2,3],beacon:[3,4],dock:[3,5]};
function initial(){return{version:SAVE_VERSION,chapter:1,x:0,z:12,crystals:0,metal:0,collected:[],cells:[],tools:[],beacons:[],buildings:[],recorder:false,antenna:false,signal:false,engineerMet:false,engineerFixed:false,navigatorMet:false,navigatorSolved:false,scoutMet:false,artifact:false,complete:false,supply:false,signalBriefed:false,signalClues:[],vaultOpen:false,blueprint:false,chapter3Complete:false,cards:{},harvestAt:{},energy:0,productionAt:Date.now(),daily:{day:'',done:[],claimed:false},streak:freshStreak(),growth:freshGrowth(),cinema:{seen:[]},team:freshTeam(),updatedAt:0};}
function sanitize(raw){const s=initial();if(!raw||![2,3,4,5,6].includes(raw.version))return s;for(const k of['recorder','antenna','signal','engineerMet','engineerFixed','navigatorMet','navigatorSolved','scoutMet','artifact','complete','supply','signalBriefed','vaultOpen','blueprint','chapter3Complete'])s[k]=raw[k]===true;s.chapter=raw.chapter===3&&raw.complete===true?3:raw.chapter===2?2:1;for(const k of['crystals','metal'])s[k]=Number.isFinite(raw[k])?Math.max(0,Math.min(10000,Math.floor(raw[k]))):0;s.x=Number.isFinite(raw.x)?Math.max(WORLD.minX,Math.min(WORLD.maxX,raw.x)):s.x;s.z=Number.isFinite(raw.z)?Math.max(WORLD.minZ,Math.min(WORLD.maxZ,raw.z)):s.z;const valid={signalClues:Object.keys(SIGNAL_NOTES),collected:resources.map(r=>r.id),cells:['cell1','cell2','cell3'],tools:['tool1','tool2'],beacons:['beacon1','beacon2','beacon3'],buildings:Object.keys(COST)};for(const k in valid)s[k]=Array.isArray(raw[k])?[...new Set(raw[k].filter(v=>valid[k].includes(v)))]:[];s.cards={};for(const id of Object.keys(CARDS)){const level=raw.cards?.[id];if(Number.isInteger(level))s.cards[id]=Math.max(0,Math.min(3,level));}syncCards(s);
s.harvestAt={};for(const id of s.collected)s.harvestAt[id]=Number.isFinite(raw.harvestAt?.[id])?raw.harvestAt[id]:Date.now();
s.energy=Number.isFinite(raw.energy)?Math.max(0,Math.min(energyCapacity(s),raw.energy)):0;
s.productionAt=Number.isFinite(raw.productionAt)&&raw.productionAt>0?raw.productionAt:Date.now();
if(raw.daily&&/^\d{4}-\d{2}-\d{2}$/.test(raw.daily.day)){s.daily={day:raw.daily.day,done:Array.isArray(raw.daily.done)?[...new Set(raw.daily.done.filter(id=>['scanner','backpack','jetpack'].includes(id)))]:[],claimed:raw.daily.claimed===true};}migrateGrowth(raw,s);return s;}
function quest(s){if(s.chapter===3){if(s.chapter3Complete)return{id:'complete3',title:'Чертёж ракеты найден',detail:'Три жизни пройдены. Развивай базу и исследуй мир; следующая жизнь — подготовка ракеты.',targets:[],fraction:1};if(!s.signalBriefed)return{id:'signalStart',title:'Новый сигнал с юга',detail:'Поговори с инженером. Обсерватория передаёт старый сигнал экспедиции.',targets:['signalStart'],fraction:0};if(s.signalClues.length<3)return{id:'signalClues',title:`Собери записи · ${s.signalClues.length}/3`,detail:'Ищи терминалы в Тихом кратере, Кристальной долине и Южной обсерватории. Сканер и карта помогут проложить путь.',targets:Object.keys(SIGNAL_NOTES).filter(id=>!s.signalClues.includes(id)),fraction:.15+s.signalClues.length*.15};if(!s.vaultOpen)return{id:'vault',title:'Расшифруй архив станции',detail:'Вернись к архивному терминалу Южной обсерватории. Введи цифры по порядку записей I, II, III.',targets:['vault'],fraction:.65};if(!s.blueprint)return{id:'blueprint',title:'Скачай чертёж ракеты',detail:'Архив разблокирован. Активируй терминал, чтобы сохранить чертёж.',targets:['blueprint'],fraction:.8};return{id:'blueprintReturn',title:'Передай чертёж инженеру',detail:'Вернись в лагерь. Команда проверит чертёж и подготовит следующую экспедицию.',targets:['blueprintReturn'],fraction:.9};}if(s.chapter===1){if(!s.recorder)return{id:'recorder',title:'Найди бортовой журнал',detail:'Обследуй аварийную капсулу. В журнале может быть сигнал экипажа.',targets:['recorder'],fraction:0};if(s.cells.length<3)return{id:'cells',title:`Найди энергоблоки · ${s.cells.length}/3`,detail:'Один блок за низким ограждением — перепрыгни его. Другой ищи между грузовыми контейнерами.',targets:['cell1','cell2','cell3'].filter(id=>!s.cells.includes(id)),fraction:.2};if(!s.antenna)return{id:'antenna',title:'Восстанови антенну',detail:'Доставь энергоблоки к вышке связи.',targets:['antenna'],fraction:.5};if(!s.signal)return{id:'signal',title:'Настрой сигнал связи',detail:'Найди пик сигнала на каждом канале терминала антенны.',targets:['antenna'],fraction:.7};return{id:'pod',title:'Вернись к капсуле',detail:'Сигнал найден! Забери координаты лагеря экипажа.',targets:['pod'],fraction:.9};}
if(s.complete)return{id:'complete',title:'Две жизни пройдены',detail:'Инженер обнаружил новый сигнал. Поговори с ним или начни третью жизнь через меню экспедиции.',targets:['engineer'],fraction:1};
if(!s.engineerMet)return{id:'engineer',title:'Найди инженера',detail:'Инженер ждёт у ремонтного модуля в лагере.',targets:['engineer'],fraction:0};if(s.tools.length<2)return{id:'tools',title:`Забери ремонтные наборы · ${s.tools.length}/2`,detail:'Один набор у скал, другой — у посадочной площадки.',targets:['tool1','tool2'].filter(id=>!s.tools.includes(id)),fraction:.1};if(!s.engineerFixed)return{id:'repair',title:'Вернись к инженеру',detail:'Передай наборы: инженер восстановит твой реактивный ранец.',targets:['engineer'],fraction:.25};if(!s.navigatorMet)return{id:'navigator',title:'Поговори со штурманом',detail:'Нужна карта безопасного маршрута через долину.',targets:['navigator'],fraction:.35};if(s.beacons.length<3)return{id:'beacons',title:`Активируй маяки · ${s.beacons.length}/3`,detail:'Третий маяк окружён разломом. Перелети его на ранце и приземлись в центре. Запоминай сообщения маяков.',targets:['beacon1','beacon2','beacon3'].filter(id=>!s.beacons.includes(id)),fraction:.45};if(!s.navigatorSolved)return{id:'route',title:'Составь маршрут со штурманом',detail:'Вернись к штурману и соедини маяки в безопасном порядке.',targets:['navigator'],fraction:.6};if(!s.scoutMet)return{id:'scout',title:'Найди разведчика',detail:'Разведчик обнаружил следы старой экспедиции возле дальнего каньона.',targets:['scout'],fraction:.7};if(!s.artifact)return{id:'artifact',title:'Забери архив экспедиции',detail:'Дойди до терминала в каньоне и скачай архив.',targets:['artifact'],fraction:.8};if(!s.buildings.includes('habitat'))return{id:'base',title:'Построй общий жилой модуль',detail:'Собери 4 кристалла и 6 металла, вернись в лагерь и открой строительство.',targets:['base'],fraction:.9};return{id:'final',title:'Собери экипаж у базы',detail:'Вернись к жилому модулю и заверши вторую жизнь.',targets:['final'],fraction:.95};}
function nearestTarget(s,p){let q=quest(s),list=q.targets.map(id=>({id,x:POINTS[id][0],z:POINTS[id][1]}));if(!s.supply)list.push({id:'supply',x:3,z:7});for(const r of resources)if(!s.collected.includes(r.id))list.push({...r});const distance=t=>Math.hypot(p.x-t.x,p.z-t.z);const nearbyQuest=list.filter(t=>q.targets.includes(t.id)&&distance(t)<=3.3).sort((a,b)=>distance(a)-distance(b));return nearbyQuest[0]||list.sort((a,b)=>distance(a)-distance(b))[0]||null;}
function interact(s,id,p){let r=resources.find(r=>r.id===id),point=r?[r.x,r.z]:POINTS[id];if(!point||Math.hypot(p.x-point[0],p.z-point[1])>3.3||p.alt>1.1)return{ok:false,text:'Подойди ближе и приземлись.'};if(id==='supply'){if(s.supply)return{ok:false,text:'Контейнер уже открыт.'};s.supply=true;syncCards(s);return{ok:true,text:'Новая карточка: рюкзак исследователя! Вместимость — 60 каждого ресурса.'};}if(r){if(s.collected.includes(id))return{ok:false,text:'Ресурсы уже собраны.'};let amount=r.type==='crystals'?2:3;if(s[r.type]+amount>capacity(s))return{ok:false,text:'Рюкзак заполнен. Потрать ресурсы или улучши карточку рюкзака.'};s.collected.push(id);s.harvestAt[id]=Date.now();s[r.type]+=amount;markDaily(s,'backpack');return{ok:true,found:r.type,text:r.type==='crystals'?'+2 кристалла':'+3 металла'};}
const q=quest(s);if(!q.targets.includes(id))return{ok:false,text:'Сначала выполни текущую задачу.'};if(q.id==='complete')return{ok:true,nextLife:true};if(q.id==='signalStart'){s.signalBriefed=true;return{ok:true,story:'signalStart'};}if(q.id==='signalClues'){s.signalClues.push(id);return{ok:true,text:SIGNAL_NOTES[id],journal:true};}if(q.id==='vault')return{ok:true,puzzle:'vault'};if(q.id==='blueprint'){s.blueprint=true;return{ok:true,story:'blueprint'};}if(q.id==='blueprintReturn'){s.chapter3Complete=true;return{ok:true,chapterEnd:3};}if(q.id==='recorder'){s.recorder=true;return{ok:true,story:'recorder'};}if(q.id==='cells'){s.cells.push(id);return{ok:true,text:`Энергоблок найден · ${s.cells.length}/3`};}if(q.id==='antenna'){s.antenna=true;syncCards(s);return{ok:true,text:'Антенна восстановлена. Настрой терминал.'};}if(q.id==='signal')return{ok:true,puzzle:'signal'};if(q.id==='pod')return{ok:true,chapterEnd:1};if(q.id==='engineer'){s.engineerMet=true;return{ok:true,story:'engineer'};}if(q.id==='tools'){s.tools.push(id);return{ok:true,text:`Ремонтный набор · ${s.tools.length}/2`};}if(q.id==='repair'){s.engineerFixed=true;syncCards(s);return{ok:true,story:'repair'};}if(q.id==='navigator'){s.navigatorMet=true;return{ok:true,story:'navigator'};}if(q.id==='beacons'){s.beacons.push(id);return{ok:true,text:BEACON_NOTES[id]+` · ${s.beacons.length}/3`};}if(q.id==='route')return{ok:true,puzzle:'route'};if(q.id==='scout'){s.scoutMet=true;return{ok:true,story:'scout'};}if(q.id==='artifact'){s.artifact=true;return{ok:true,story:'artifact'};}if(q.id==='base')return{ok:true,builder:true};if(q.id==='final'){s.complete=true;return{ok:true,chapterEnd:2};}return{ok:false,text:'Нечего активировать.'};}
function solve(s,type,value){if(type==='vault'&&quest(s).id==='vault'){if(Array.isArray(value)&&value.length===3&&value.every((v,i)=>Number.isInteger(v)&&v===[7,3,2][i])){s.vaultOpen=true;return{ok:true,text:'Архив открыт. Скачай чертёж из терминала.'};}return{ok:false,text:'Код не совпал. Проверь порядок записей I, II, III в журнале.'};}if(type==='signal'&&quest(s).id==='signal'){if(value.length===3&&value.every((v,i)=>Math.abs(v-[32,68,45][i])<=3)){s.signal=true;return{ok:true,text:'Связь установлена. Экипаж найден!'};}return{ok:false,text:'Сигнал шумит. Найди более сильный отклик каждого канала.'};}if(type==='route'&&quest(s).id==='route'){if(JSON.stringify(value)===JSON.stringify(['cyan','gold','white'])){s.navigatorSolved=true;syncCards(s);return{ok:true,text:'Безопасный маршрут сохранён.'};}return{ok:false,text:'Маршрут не соединён. Сопоставь сообщения трёх маяков.'};}return{ok:false,text:'Терминал пока недоступен.'};}
function build(s,type,p){if(s.chapter<2||!s.artifact)return{ok:false,text:'Строительство откроется после задания разведчика.'};if(Math.hypot(p.x+5,p.z+7)>7||p.alt>1)return{ok:false,text:'Вернись на строительную площадку лагеря.'};if(!COST[type])return{ok:false,text:'Неизвестный модуль.'};if(s.buildings.includes(type))return{ok:false,text:'Модуль уже построен.'};if(type==='workshop'&&!s.engineerFixed)return{ok:false,text:'Сначала помоги инженеру.'};if(type==='solar'&&level(s,'workshop')<1)return{ok:false,text:'Сначала построй мастерскую.'};if(type==='beacon'&&level(s,'workshop')<2)return{ok:false,text:'Нужна мастерская уровня 2.'};if(type==='dock'&&level(s,'workshop')<3)return{ok:false,text:'Нужна мастерская уровня 3.'};let [c,m]=COST[type];if(s.crystals<c||s.metal<m)return{ok:false,text:`Нужно ${c} кристалла и ${m} металла.`};s.crystals-=c;s.metal-=m;s.buildings.push(type);syncCards(s);if(type==='solar')s.productionAt=Date.now();return{ok:true,text:'Модуль установлен!'};}
function nextChapter(s){if(s.chapter===1&&quest(s).id==='pod'){s.chapter=2;s.x=0;s.z=10;return true;}if(s.chapter===2&&s.complete){s.chapter=3;s.x=4;s.z=3;return true;}return false;}

const CARDS={
 scanner:{name:'Сканер',subtitle:'СЛЕДЫ В ПЫЛИ',category:'Исследование',chapter:1,unlock:'Восстанови антенну в жизни #1',point:'antenna',costs:[[2,3],[4,5]],ready:s=>s.antenna},
 backpack:{name:'Рюкзак исследователя',subtitle:'ВСЁ НУЖНОЕ РЯДОМ',category:'Снаряжение',chapter:1,unlock:'Открой контейнер рядом с капсулой',point:'supply',costs:[[2,3],[4,5]],ready:s=>s.supply},
 jetpack:{name:'Реактивный ранец',subtitle:'ВЫШЕ ГОРИЗОНТА',category:'Снаряжение',chapter:2,unlock:'Помоги инженеру починить ранец',point:'engineer',costs:[[3,4],[5,6]],ready:s=>s.engineerFixed},
 workshop:{name:'Мастерская',subtitle:'МЕСТО НОВЫХ ИДЕЙ',category:'База',chapter:2,unlock:'Получи архив и построй мастерскую',point:'workshop',costs:[[3,4],[5,6]],ready:s=>s.engineerFixed&&s.buildings.includes('workshop')},
 solar:{name:'Солнечная станция',subtitle:'ЭНЕРГИЯ НОВОГО ДОМА',category:'База',chapter:2,unlock:'Построй мастерскую и солнечную станцию',point:'solar',costs:[[3,4],[5,6]],ready:s=>s.buildings.includes('solar')},
 drone:{name:'Дрон-разведчик',subtitle:'ТВОЙ НАПАРНИК В НЕБЕ',category:'Команда',chapter:2,unlock:'Восстанови маршрут со штурманом',point:'navigator',costs:[[3,4],[5,6]],ready:s=>s.navigatorSolved}
};
function level(s,id){return s.cards?.[id]||0;}
function syncCards(s){s.cards=s.cards||{};const unlocked=[];for(const[id,c]of Object.entries(CARDS)){if(c.ready(s)){if(!s.cards[id]){s.cards[id]=1;unlocked.push(id);}}else delete s.cards[id];}return unlocked;}
function capacity(s){return[40,60,90,140][level(s,'backpack')];}
function fuelDrain(s){return[3.7,3.7,2.8,2.1][level(s,'jetpack')];}
function combo(s){return level(s,'scanner')>0&&level(s,'drone')>0&&s.navigatorSolved;}
function scanRadius(s){return[14,22,32,44][level(s,'scanner')]*(combo(s)?1.2:1);}
function droneRadius(s){return[0,12,20,30][level(s,'drone')]*(s.buildings.includes('dock')?1.25:1);}
function energyCapacity(s){return[0,12,24,40][level(s,'solar')];}
function energyRate(s){return[0,6,12,20][level(s,'solar')];}
function cardEffect(s,id,l=level(s,id)){switch(id){case'scanner':return`Радиус поиска: ${[14,22,32,44][l]} м`;case'backpack':return`Вмещает по ${[40,60,90,140][l]} ресурсов`;case'jetpack':return`Полёт: ~${Math.floor(100/[3.7,3.7,2.8,2.1][l])} сек`;case'workshop':return['Построй модуль в лагере','Чертёж станции · кристаллы из энергии','Чертёж маяка · металл из энергии','Чертёж дока · усиление дрона'][l];case'solar':return`${[0,6,12,20][l]} энергии/ч · запас ${[0,12,24,40][l]}`;case'drone':return`Разведка рядом: ${[0,12,20,30][l]} м`;}}
function upgrade(s,id,now=Date.now()){const c=Object.hasOwn(CARDS,id)?CARDS[id]:null,l=level(s,id);if(!c||!l||l>=3)return{ok:false,text:!l?'Карточка ещё не открыта.':'Максимальный уровень.'};const[crystals,metal]=c.costs[l-1];if(s.crystals<crystals||s.metal<metal)return{ok:false,text:`Нужно ${crystals} кристалла и ${metal} металла.`};tick(s,now);s.crystals-=crystals;s.metal-=metal;s.cards[id]=l+1;return{ok:true,text:`${c.name} · уровень ${l+1}`};}
function tick(s,now=Date.now()){let changed=false;for(const id of [...s.collected]){const at=s.harvestAt[id];if(!Number.isFinite(at)||at>now){s.harvestAt[id]=now;changed=true;}else if(now-at>=90000){s.collected=s.collected.filter(v=>v!==id);delete s.harvestAt[id];changed=true;}}
if(!s.productionAt||now<s.productionAt){s.productionAt=now;return changed;}const elapsed=Math.min(now-s.productionAt,86400000);if(elapsed>=1000){const energy=s.energy;s.energy=Math.min(energyCapacity(s),s.energy+elapsed/3600000*energyRate(s));s.productionAt=now;changed=changed||s.energy!==energy;}return changed;}
function craft(s,type,p){if(s.chapter<2||Math.hypot(p.x+5,p.z+7)>7||p.alt>1)return{ok:false,text:'Для изготовления вернись в лагерь и приземлись.'};if(!['crystals','metal'].includes(type))return{ok:false,text:'Неизвестный рецепт.'};const recipe={crystals:{level:1,energy:3},metal:{level:2,energy:2}}[type];if(!recipe||level(s,'workshop')<recipe.level)return{ok:false,text:'Сначала улучши мастерскую.'};if(s.energy<recipe.energy)return{ok:false,text:`Нужно ${recipe.energy} энергии солнечной станции.`};if(s[type]>=capacity(s))return{ok:false,text:'Рюкзак заполнен.'};s.energy-=recipe.energy;s[type]++;return{ok:true,text:type==='crystals'?'+1 кристалл изготовлен':'+1 металл изготовлен'};}
function today(now=Date.now()){const d=new Date(now);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function daily(s,now=Date.now()){const day=today(now);if(s.daily.day!==day)s.daily={day,done:[],claimed:false};return s.daily;}
function markDaily(s,id,now=Date.now()){if(!level(s,id))return;const d=daily(s,now);if(!d.done.includes(id))d.done.push(id);}
function claimDaily(s,now=Date.now()){const d=daily(s,now);if(d.claimed||!['scanner','backpack','jetpack'].every(id=>d.done.includes(id)))return{ok:false,text:'Выполни три задания экспедиции.'};if(s.crystals+4>capacity(s)||s.metal+6>capacity(s))return{ok:false,text:'Освободи место: награда — 4 кристалла и 6 металла.'};d.claimed=true;s.crystals+=4;s.metal+=6;return{ok:true,text:'Экспедиция дня: +4 кристалла и +6 металла!'};}
function discoveries(s,p,radius){const list=resources.filter(r=>!s.collected.includes(r.id)).map(r=>({...r,label:r.type==='crystals'?'Кристаллы':'Металл'}));if(!s.supply)list.push({id:'supply',x:3,z:7,label:'Аварийный контейнер'});return list.filter(r=>Math.hypot(r.x-p.x,r.z-p.z)<=radius).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z));}

function noise(x,z){return Math.sin(x*.18+Math.sin(z*.13))*Math.cos(z*.19)*.33+Math.sin(x*.54+z*.31)*.09;}
function height(x,z,chapter=1){let path=Math.exp(-((x-Math.sin(z*.07)*5)**2)/30);let h=noise(x,z)+(.065*Math.sin(x*.41+z*.24)+.046*Math.sin(z*.53-x*.33)+.027*Math.sin(x*.63+z*.67))*(1-path*.65);for(const[cx,cz,r,d]of [[16,17,8,.8],[-20,14,7,.7],[24,-32,6,.55],[-55,-50,13,1.3],[58,-30,11,.7],[35,55,9,.6]]){let q=Math.hypot(x-cx,z-cz)/r;h+=d*(.35*Math.exp(-((q-1.05)**2)/.025)-Math.exp(-q*q*2.5));}if(chapter>=2){const radius=Math.hypot(x-FIELD.x,z-FIELD.z);h+=2.4*Math.exp(-radius*radius/75);h-=2.2*Math.exp(-((radius-5.2)**2)/.85);h-=.45*Math.exp(-((x+24)**2+(z+39)**2)/70);}return h;}
function surfaceHeight(x,z,chapter=1){const sx=-5,sz=-2;return Math.hypot(x-sx,z-sz)<3.55?Math.max(height(x,z,chapter),height(sx,sz,chapter)+.14):height(x,z,chapter);}
return{SIGNAL_NOTES,WORLD,REGIONS,FIELD,BARRIERS,BEACON_NOTES,obstacleAt,signalStrength,surfaceHeight,CARDS,level,syncCards,capacity,fuelDrain,combo,scanRadius,droneRadius,energyCapacity,energyRate,cardEffect,upgrade,tick,craft,daily,markDaily,claimDaily,discoveries,KEY,POINTS,SAVE_VERSION,CINEMA_IDS,CREW_IDS,SOCIAL_IDS,BADGES,today,resources,COST,initial,sanitize,quest,nearestTarget,interact,solve,build,nextChapter,height};});
