if(typeof _t==='undefined'&&typeof require==='function')require('./i18n.js');
/* Four optional expeditions with persistent progress and explicit, single-use rewards. */
(function(root){'use strict';const C=root.MoonCore||(typeof require==='function'?require('./core.js'):null);if(!C||C.CONTRACTS)return;root.MoonCore=C;
const initial=C.initial,sanitize=C.sanitize,quest=C.quest,nearest=C.nearestTarget,interact=C.interact,solve=C.solve,discoveries=C.discoveries;
const CONTRACTS={
 salvage:{name:_t('exp.sledy_kratere'),region:_t('core.tihiy_krater'),type:_t('exp.poisk'),detail:_t('exp.proskaniruy_krater'),unlock:_t('core.naydi_bortovoy'),ready:s=>s.recorder,reward:[6,9],guide:'salvageBase',nodes:['salvage1','salvage2','salvage3']},
 survey:{name:_t('exp.serdtse_doliny'),region:_t('core.kristalnaya_dolina'),type:_t('core.issledovanie'),detail:_t('exp.skanerom_naydi'),unlock:_t('exp.vosstanovi_antennu'),ready:s=>s.antenna,reward:[8,6],guide:'surveyBase',nodes:['sample1','sample2','sample3']},
 relay:{name:_t('exp.stantsiya_ozhivaet'),region:_t('core.yuzhnaya_observato'),type:_t('exp.golovolomka'),detail:_t('exp.poverni_segmenty'),unlock:_t('exp.poluchi_arhiv'),ready:s=>s.artifact,reward:[5,10],guide:'relayTerminal',nodes:['relayTerminal']},
 flight:{name:_t('exp.nad_razlomom'),region:_t('exp.severnyy_hrebet'),type:_t('exp.marshrut'),detail:_t('exp.proydi_pyat'),unlock:_t('exp.pochini_reaktivnyy'),ready:s=>s.engineerFixed,reward:[7,8],guide:'flight1',nodes:['flight1','flight2','flight3','flight4','flight5']}
};
Object.assign(C.POINTS,{salvageBase:[-55,-55],salvage1:[-62,-45],salvage2:[-50,-51],salvage3:[-58,-63],surveyBase:[58,-35],sample1:[51,-26],sample2:[59,-23],sample3:[65,-31],relayTerminal:[32,54],flight1:[-12,-30],flight2:[-5,-40],flight3:[7,-45],flight4:[17,-36],flight5:[12,-25]});
const RELAY_START=[1,0,3,1,1,1],TYPES=['straight','elbow','elbow','straight','elbow','straight'];
function defaults(){return{active:'',progress:Object.fromEntries(Object.keys(CONTRACTS).map(id=>[id,{found:[],taken:[],done:false,claimed:false,step:0,seconds:0,best:null,rotations:RELAY_START.slice()}]))};}
function field(s){if(!s.expeditions)s.expeditions=defaults();return s.expeditions;}
C.initial=function(){const s=initial();s.expeditions=defaults();return s;};
C.sanitize=function(raw){const s=sanitize(raw),e=defaults(),r=raw?.expeditions;if(r&&typeof r==='object'){for(const[id,c]of Object.entries(CONTRACTS)){const p=r.progress?.[id];if(!p||typeof p!=='object')continue;const out=e.progress[id];for(const key of['found','taken'])out[key]=Array.isArray(p[key])?[...new Set(p[key].filter(n=>c.nodes.includes(n)))]:[];out.found=[...new Set([...out.found,...out.taken])];out.done=p.done===true;out.claimed=out.done&&p.claimed===true;out.step=Number.isInteger(p.step)?Math.max(0,Math.min(c.nodes.length,p.step)):0;out.seconds=Number.isFinite(p.seconds)?Math.max(0,Math.min(90,p.seconds)):0;if(id==='flight'&&out.step>=c.nodes.length){out.step=0;out.seconds=0;}out.best=Number.isFinite(p.best)&&p.best>=0&&p.best<=90?p.best:null;if(Array.isArray(p.rotations)&&p.rotations.length===6&&p.rotations.every(n=>Number.isInteger(n)&&n>=0&&n<=3))out.rotations=p.rotations.slice();}if(Object.hasOwn(CONTRACTS,r.active)&&CONTRACTS[r.active].ready(s)&&(!e.progress[r.active].done||r.active==='flight'))e.active=r.active;}s.expeditions=e;return s;};
function active(s){const e=field(s);return Object.hasOwn(CONTRACTS,e.active)?e.active:'';}
C.mainQuest=quest;
C.quest=function(s){const id=active(s);if(!id)return quest(s);const c=CONTRACTS[id],p=field(s).progress[id];let targets,title,detail=c.detail;
 if(id==='flight'){targets=[c.nodes[p.step]||c.nodes[0]];title=c.name+' · '+p.step+'/5';detail=p.step?`${_t('exp.tochka_5',{step:p.step+1,seconds:Math.ceil(90-p.seconds)})} `+c.detail:c.detail;}
 else if(id==='relay'){targets=c.nodes;title=c.name;}
 else{targets=p.found.filter(n=>!p.taken.includes(n));if(p.found.length<c.nodes.length)targets.push(c.guide);if(!targets.length)targets=[c.guide];title=c.name+' · '+p.taken.length+'/3';detail=(p.found.length<c.nodes.length?_t('exp.nuzhen_skaner')+' ':'')+c.detail;}
 return{id:'contract-'+id,title,detail,targets,fraction:id==='flight'?p.step/5:id==='relay'?0:p.taken.length/3,contract:true};};
C.beginContract=function(s,id){if(!Object.hasOwn(CONTRACTS,id))return{ok:false,text:_t('exp.neizvestnaya_ekspe')};const c=CONTRACTS[id],p=field(s).progress[id];if(!c.ready(s))return{ok:false,text:c.unlock+'.'};if(p.done&&id!=='flight')return{ok:false,text:_t('exp.ekspeditsiya_uzhe')};field(s).active=id;if(id==='flight'){p.step=0;p.seconds=0;}return{ok:true,text:_t('exp.otmechena_kompase',{name:c.name})};};
C.suspendContract=function(s){field(s).active='';return{ok:true,text:_t('exp.prodolzhaem_syuzhe')};};
C.claimContract=function(s,id){if(!Object.hasOwn(CONTRACTS,id))return{ok:false,text:_t('exp.neizvestnaya_ekspe')};const p=field(s).progress[id],c=CONTRACTS[id];if(!p.done||p.claimed)return{ok:false,text:p.claimed?_t('exp.nagrada_uzhe'):_t('exp.snachala_zavershi')};const[a,b]=c.reward;if(s.crystals+a>C.capacity(s)||s.metal+b>C.capacity(s))return{ok:false,text:_t('exp.osvobodi_mesto')};p.claimed=true;s.crystals+=a;s.metal+=b;return{ok:true,text:`${_t('exp.nagrada_kristallov',{a:a,b:b})}`};};
C.scanContract=function(s,p,radius){const id=active(s);if(!['salvage','survey'].includes(id))return 0;const task=field(s).progress[id];let count=0;for(const node of CONTRACTS[id].nodes){const[x,z]=C.POINTS[node];if(!task.found.includes(node)&&Math.hypot(x-p.x,z-p.z)<=radius){task.found.push(node);count++;}}return count;};
function finish(s,id){const p=field(s).progress[id];p.done=true;field(s).active='';return{ok:true,contractDone:id,text:_t('exp.zavershena_zaberi',{name:CONTRACTS[id].name})};}
C.advanceContract=function(s,p,dt){if(active(s)!=='flight')return null;const task=field(s).progress.flight,c=CONTRACTS.flight;if(task.step>=c.nodes.length){task.step=0;task.seconds=0;}if(task.step)task.seconds=Math.min(90,task.seconds+Math.max(0,dt));if(task.seconds>=90){task.step=0;task.seconds=0;field(s).active='';return{ok:false,text:_t('exp.vremya_marshruta')};}const[x,z]=C.POINTS[c.nodes[task.step]];if(Math.hypot(p.x-x,p.z-z)>2.8||task.step===1&&p.alt<1.2)return null;task.step++;if(task.step===5){task.best=task.best===null?task.seconds:Math.min(task.best,task.seconds);return finish(s,'flight');}return{ok:true,text:`${_t('exp.kontrolnaya_tochka',{step:task.step})} `+(task.step===1?_t('exp.vtoraya_tochka'):_t('exp.dvigaysya_sleduyus'))};};
C.nearestTarget=function(s,p){const id=active(s);if(!id)return nearest(s,p);const targets=C.quest(s).targets.map(node=>({id:node,x:C.POINTS[node][0],z:C.POINTS[node][1]})).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z));const close=targets.find(n=>Math.hypot(n.x-p.x,n.z-p.z)<=3.3);return close||nearest(s,p);};
C.interact=function(s,id,p){const task=active(s),c=CONTRACTS[task];if(c&&(id===c.guide||c.nodes.includes(id))){const[x,z]=C.POINTS[id];if(Math.hypot(p.x-x,p.z-z)>3.3||p.alt>1.1)return{ok:false,text:_t('core.podoydi_blizhe')};if(task==='flight')return{ok:true,text:_t('exp.sleduy_tochkam')};if(task==='relay')return{ok:true,puzzle:'relay'};const f=field(s).progress[task];if(id===c.guide)return{ok:true,text:_t('exp.vklyuchi_skaner')};if(!f.found.includes(id))return{ok:false,text:_t('exp.snachala_issleduy')};if(f.taken.includes(id))return{ok:false,text:_t('exp.etot_obekt')};f.taken.push(id);if(f.taken.length===c.nodes.length)return finish(s,task);return{ok:true,text:(task==='survey'?_t('exp.proba_sohranena'):_t('exp.gruz_nayden'))+' · '+f.taken.length+'/3'};}return interact(s,id,p);};
function ports(i,rotation){return(TYPES[i]==='straight'?[1,3]:[0,1]).map(n=>(n+rotation)%4);}
C.relayTrace=function(rotations){if(!Array.isArray(rotations)||rotations.length!==6||!rotations.every(n=>Number.isInteger(n)&&n>=0&&n<=3))return{connected:false,powered:[]};const powered=[],seen=new Set();let index=0,incoming=3;while(!seen.has(index)){seen.add(index);const exits=ports(index,rotations[index]);if(!exits.includes(incoming))return{connected:false,powered};powered.push(index);const out=exits.find(n=>n!==incoming),col=index%3,row=Math.floor(index/3);if(index===5&&out===1)return{connected:true,powered};const x=col+[0,1,0,-1][out],y=row+[-1,0,1,0][out];if(x<0||x>=3||y<0||y>=2)return{connected:false,powered};index=y*3+x;incoming=(out+2)%4;}return{connected:false,powered};};
C.solve=function(s,type,value){if(type!=='relay')return solve(s,type,value);if(active(s)!=='relay'||!CONTRACTS.relay.ready(s))return{ok:false,text:_t('exp.stantsiya_poka')};if(!C.relayTrace(value).connected)return{ok:false,text:_t('exp.kontur_razorvan')};field(s).progress.relay.rotations=value.slice();return finish(s,'relay');};
C.discoveries=function(s,p,radius){const list=discoveries(s,p,radius),id=active(s);if(['salvage','survey'].includes(id)){const f=field(s).progress[id];for(const node of f.found.filter(n=>!f.taken.includes(n))){const[x,z]=C.POINTS[node];if(Math.hypot(x-p.x,z-p.z)<=radius)list.push({id:node,x,z,label:id==='survey'?_t('exp.mineralnaya_proba'):_t('exp.utselevshiy_gruz')});}}return list;};
C.contractMarkers=function(s){const id=active(s);if(!id)return[];const c=CONTRACTS[id],p=field(s).progress[id],nodes=id==='flight'?[c.nodes[p.step]].filter(Boolean):id==='relay'?c.nodes:p.found.filter(n=>!p.taken.includes(n));return nodes.map(n=>({id:n,x:C.POINTS[n][0],z:C.POINTS[n][1],type:id==='flight'?'checkpoint':id==='relay'?'relay':id==='survey'?'sample':'cache'}));};
C.contractStatus=function(s,id){const p=field(s).progress[id];return p.claimed?_t('exp.nagrada_poluchena'):p.done?_t('exp.nagrada_zhdet'):active(s)===id?_t('exp.rabote'):CONTRACTS[id].ready(s)?_t('exp.dostupna'):CONTRACTS[id].unlock;};
C.CONTRACTS=CONTRACTS;C.RELAY_START=RELAY_START;C.relayPorts=ports;
})(globalThis);
