(()=>{'use strict';const $=s=>document.querySelector(s),Core=MoonCore;let state=Core.initial();try{state=Core.sanitize(JSON.parse(localStorage.getItem(Core.KEY)));}catch{}Core.tick(state);let renderer;try{renderer=new MoonRenderer($('#world'));}catch(e){$('#error').hidden=false;$('#error').textContent='Не удалось запустить 3D-мир. '+e.message;$('#cover').hidden=true;return;}
const spawn=renderer.safeSpawn(state.x,state.z,state);const player={x:spawn.x,z:spawn.z,alt:0,yaw:-Math.PI/2,speed:0,fuel:100,velocity:0};let camYaw=0,camPitch=0,flight=false,keys={},joy={x:0,y:0},time=0,last=0,running=false,scanUntil=0,near=null,saveBad=false,toastTimer,uiTime=0,activePuzzle=null,route=[],selectedCard=null,tracked=null,flightSeconds=0,flightDay=Core.daily(state).day,economyTime=0,renderTime=0;
const STORIES={recorder:['БОРТОВОЙ ЖУРНАЛ','Последний сигнал','«Капсула повреждена. Три энергоблока разбросаны в долине. Восстанови питание антенны — она найдёт сигнал экипажа». Журнал сохранён в твоём костюме.'],engineer:['ENGINEER · ИНЖЕНЕР','Ремонт начинается','«Рад тебя видеть! Для реактивного ранца нужны два ремонтных набора. Один остался у западных скал, второй — возле корабля. Принеси их, и мы снова сможем летать».'],repair:['ENGINEER · ИНЖЕНЕР','Ранец восстановлен','«Готово! Кнопка ранца поднимает тебя над поверхностью. Следи за запасом энергии; на земле она восстанавливается. Теперь найди штурмана».'],navigator:['NAVIGATOR · ШТУРМАН','Карта из трёх сигналов','«Активируй три маяка, чтобы я составил карту долины. Третий находится на высокой площадке. Безопасная последовательность: бирюзовый, золотой, белый. Вернись ко мне, когда маяки заработают».'],scout:['SCOUT · РАЗВЕДЧИК','Следы старой экспедиции','«В дальнем каньоне сохранился терминал с архивом. Забери данные: там могут быть чертежи для общей базы. Метка уже на твоём компасе».'],artifact:['АРХИВ ЭКСПЕДИЦИИ','Чертежи найдены','В архиве сохранились схемы жилого модуля, солнечной батареи и маяка. Вернись на площадку лагеря. Для первого модуля нужны 4 кристалла и 6 металла — их можно собрать в долине.']};
Object.assign(STORIES,{signalStart:['ЖИЗНЬ #3 · ТАЙНА СИГНАЛА','Станция отвечает','«Южная обсерватория передаёт сигнал старой экспедиции. Три записи хранят части кода: в Кристальной долине, Тихом кратере и у обсерватории. Прочитай их, открой архив и выясни, что осталось на станции».'],blueprint:['АРХИВ СТАНЦИИ','Чертёж ракеты','В архиве найден полный чертёж ракеты и журнал её испытаний. Чертёж сохранён в костюме. Передай его инженеру в лагере — команда сможет подготовить следующий этап экспедиции.']});
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,2900);}
let savedBody='';function save(){state.x=player.x;state.z=player.z;const stamp=state.updatedAt;state.updatedAt=0;const body=JSON.stringify(state);state.updatedAt=body===savedBody&&stamp?stamp:Date.now();savedBody=body;window.MoonGame?.onSave?.(state);try{localStorage.setItem(Core.KEY,JSON.stringify(state));$('#save').textContent='Прогресс сохранён на устройстве';saveBad=false;}catch{if(!saveBad)toast('Браузер не разрешает сохранение. Не закрывай игру до конца главы.');saveBad=true;$('#save').textContent='Сохранение недоступно';}}
function resetControls(){const stick=$('#joystick'),world=$('#world');if(joyId!==null&&stick.hasPointerCapture?.(joyId))stick.releasePointerCapture(joyId);if(lookId!==null&&world.hasPointerCapture?.(lookId))world.releasePointerCapture(lookId);joyId=lookId=null;joy={x:0,y:0};keys={};$('#thumb').style.transform='';}
function openDialog(id){resetControls();$('#'+id).showModal();}
function hud(){Core.syncCards(state);let q=Core.quest(state);$('#card-count').textContent=Object.keys(state.cards).length+'/6';$('#crystals').textContent=state.crystals;$('#metal').textContent=state.metal;$('#hud-energy').textContent=Math.floor(state.energy);$('#chapter-title').textContent=q.contract?'ПОЛЕВАЯ ЭКСПЕДИЦИЯ':state.chapter===1?'ЖИЗНЬ #1 · ПРОБУЖДЕНИЕ':state.chapter===2?'ЖИЗНЬ #2 · ЭКИПАЖ':'ЖИЗНЬ #3 · ТАЙНА СИГНАЛА';$('#objective').textContent=q.title;$('#detail').textContent=q.detail;$('#progress-fill').style.width=(q.fraction*100)+'%';$('#fly span').textContent=state.engineerFixed?(flight?'Посадка':'Ранец'):'Прыжок';$('#build').style.opacity=state.artifact?1:.5;$('#next-life').hidden=!(state.chapter===2&&state.complete);}
function cover(){let ch=state.chapter;$('#cover').hidden=false;$('#cover-title').innerHTML=ch===1?'Жизнь #1<br>Пробуждение':ch===2?'Жизнь #2<br>Экипаж':'Жизнь #3<br>Тайна сигнала';$('#cover-text').textContent=ch===3?'Обсерватория снова передаёт сигнал. Найди три записи старой экспедиции, расшифруй архив и забери чертёж ракеты.':ch===1?'После аварийной посадки связь с экипажем исчезла. Найди журнал, восстанови антенну и выясни, кто выжил.':'Ты нашёл лагерь. Помоги инженеру, восстанови карту со штурманом и отправляйся на разведку. Вместе вы построите новую базу.';$('.cover-art').style.backgroundImage=`linear-gradient(180deg,#081e2c00 20%,#07192770 55%,#071927ff 90%),url('assets/world-cover-chapter${ch}-v29.png')`;$('#begin').innerHTML=(state.recorder||state.chapter>=2?'Продолжить экспедицию':'Начать экспедицию')+' <span>→</span>';}
$('#begin').onclick=()=>{running=true;$('#cover').hidden=true;toast('Левый джойстик — ходить. Свайп по миру — вращать камеру. Карта — выбрать район.');hud();};cover();hud();

function showExpeditions(){
 const list=$('#expeditions-list');list.innerHTML='';
 for(const[id,c]of Object.entries(Core.CONTRACTS)){
  const progress=state.expeditions.progress[id],row=document.createElement('article');row.className='contract-card';row.dataset.contract=id;
  const type=document.createElement('small');type.textContent=c.region+' · '+c.type;
  const title=document.createElement('h3');title.textContent=c.name;
  const description=document.createElement('p');description.textContent=c.detail;
  const status=document.createElement('p');status.className='contract-status';status.textContent=Core.contractStatus(state,id)+(progress.best===null?'':' · Рекорд '+progress.best.toFixed(1)+' сек');
  const reward=document.createElement('span');reward.className='contract-reward';reward.textContent=c.reward[0]+' ◆ + '+c.reward[1]+' ▣';
  const action=document.createElement('button');action.id='contract-'+id;action.className='primary';action.disabled=!c.ready(state)||progress.done&&progress.claimed&&id!=='flight';
  const claim=progress.done&&!progress.claimed;action.textContent=claim?'Забрать награду':state.expeditions.active===id?'Продолжить':progress.done&&id==='flight'?'Повторить маршрут':'Начать экспедицию';
  action.onclick=()=>{if(claim){const r=Core.claimContract(state,id);$('#expeditions-feedback').textContent=r.text;if(r.ok){save();hud();showExpeditions();}return;}const r=state.expeditions.active===id?{ok:true,text:'Продолжаем экспедицию.'}:Core.beginContract(state,id);if(r.ok){tracked=null;$('#expeditions').close();result(r);}else $('#expeditions-feedback').textContent=r.text;};
  row.append(type,title,description,status,reward,action);list.append(row);
 }
 $('#expeditions-wallet').textContent=wallet();if(!$('#expeditions').open)openDialog('expeditions');
}
$('#expeditions-button').onclick=()=>{$('#chapters').close();$('#expeditions-feedback').textContent='';showExpeditions();};
$('#map-expeditions').onclick=()=>{$('#world-map').close();$('#expeditions-feedback').textContent='';showExpeditions();};
$('#expeditions-close').onclick=()=>$('#expeditions').close();
$('#resume-story').onclick=()=>{$('#expeditions').close();result(Core.suspendContract(state));};
function showRelay(){
 activePuzzle='relay';route=state.expeditions.progress.relay.rotations.slice();$('#puzzle-content').innerHTML='';$('#puzzle-feedback').textContent='';$('#puzzle-role').textContent='ОБСЕРВАТОРИЯ · ПИТАНИЕ';$('#puzzle-title').textContent='Восстанови силовую линию';$('#puzzle-text').textContent='Нажимай на сегменты, чтобы повернуть их на четверть оборота. Вход — слева вверху, выход — справа внизу. Бирюзовый цвет показывает путь питания.';
 const grid=document.createElement('div');grid.className='relay-grid';const buttons=[];
 const update=()=>{const trace=Core.relayTrace(route);buttons.forEach((b,i)=>{const ports=Core.relayPorts(i,route[i]),ends=[[32,4],[60,32],[32,60],[4,32]];b.innerHTML='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="'+ports.map(n=>'M32 32L'+ends[n][0]+' '+ends[n][1]).join('')+'"/></svg><span>'+String(i+1)+'</span>';b.dataset.powered=String(trace.powered.includes(i));b.setAttribute('aria-label','Сегмент '+(i+1)+', поворот '+route[i]*90+' градусов, '+(trace.powered.includes(i)?'под напряжением':'без питания'));});state.expeditions.progress.relay.rotations=route.slice();$('#puzzle-feedback').textContent=trace.connected?'Линия соединена. Подтверди запуск станции.':'Поверни сегменты и доведи питание до выхода.';save();};
 for(let i=0;i<6;i++){const b=document.createElement('button');b.id='relay-tile-'+i;b.onclick=()=>{route[i]=(route[i]+1)%4;update();};buttons.push(b);grid.append(b);}
 $('#puzzle-content').append(grid);update();openDialog('puzzle');
}

$('#story-close').onclick=()=>$('#story').close();function story(id){const[role,title,text]=STORIES[id];$('#story-role').textContent=role;$('#story-title').textContent=title;$('#story-text').textContent=text;openDialog('story');}
function result(r){if(!r.ok){toast(r.text);return;}let fresh=Core.syncCards(state);save();hud();ui();if(fresh.length)toast('Открыты карточки: '+fresh.map(id=>Core.CARDS[id].name).join(', '));if(r.text)toast(r.text);if(r.story)story(r.story);if(r.puzzle)showPuzzle(r.puzzle);if(r.builder)showBuilder();if(r.contractDone)showExpeditions();if(r.chapterEnd)chapterEnd(r.chapterEnd);if(r.nextLife)enterNextLife();}
$('#interact').onclick=()=>{if(!near){toast('Подойди к предмету или к отметке задания.');return;}result(Core.interact(state,near.id,player));};
function showPuzzle(type){if(type==='relay'){showRelay();return;}if(type==='vault'){showVault();return;}activePuzzle=type;route=[];$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent=type==='signal'?'АНТЕННА · КАЛИБРОВКА':'NAVIGATOR · МАРШРУТ';$('#puzzle-title').textContent=type==='signal'?'Поймай сигнал экипажа':'Три маяка, один путь';$('#puzzle-text').textContent=type==='signal'?'Медленно меняй частоту каждого канала. Найди максимум отклика: все три индикатора должны стать зелёными.':'Соедини маяки по их сообщениям. Выбери начало, промежуточный сигнал и конец пути.';if(type==='signal'){[32,68,45].forEach((target,i)=>{let row=document.createElement('div');row.className='slider-row';let label=document.createElement('label');label.textContent='Канал '+(i+1);let output=document.createElement('b');output.textContent='0';label.append(output);let input=document.createElement('input');input.type='range';input.min='0';input.max='100';input.value='0';input.setAttribute('aria-label','Частота канала '+(i+1));let meter=document.createElement('div');meter.className='signal-meter';let fill=document.createElement('i');meter.append(fill);const tune=()=>{const strength=Core.signalStrength(i,input.value);output.textContent=strength+'% отклик';fill.style.width=strength+'%';meter.dataset.locked=strength>=79?'true':'false';};input.oninput=tune;tune();row.append(label,input,meter);$('#puzzle-content').append(row);});}else{let notes=document.createElement('p');notes.className='beacon-notes';notes.textContent=['beacon3','beacon1','beacon2'].filter(id=>state.beacons.includes(id)).map(id=>Core.BEACON_NOTES[id]).join('\n');$('#puzzle-content').append(notes);let choices=document.createElement('div');choices.className='route-buttons';for(let [id,title]of[['white','Белый'],['cyan','Бирюзовый'],['gold','Золотой']]){let b=document.createElement('button');b.dataset.node=id;b.textContent=title;b.onclick=()=>{if(route.length===3)route=[];route.push(id);$('#route-result').textContent=route.map(v=>({cyan:'◆',gold:'●',white:'◇'})[v]).join(' → ');};choices.append(b);}let output=document.createElement('p');output.id='route-result';$('#puzzle-content').append(choices,output);}openDialog('puzzle');}
$('#puzzle-submit').onclick=()=>{let value=activePuzzle==='vault'?[...$('#puzzle-content').querySelectorAll('input')].map(e=>e.value.trim()===''?NaN:Number(e.value)):activePuzzle==='signal'?[...$('#puzzle-content').querySelectorAll('input')].map(e=>Number(e.value)):route;let r=Core.solve(state,activePuzzle,value);if(r.ok){$('#puzzle').close();result(r);}else{$('#puzzle-feedback').textContent=r.text;if(activePuzzle==='route'){route=[];$('#route-result').textContent='';}}};$('#puzzle-close').onclick=()=>$('#puzzle').close();
function enterNextLife(){if(!Core.nextChapter(state))return;Core.suspendContract(state);const safe=renderer.safeSpawn(state.x,state.z,state);player.x=safe.x;player.z=safe.z;player.alt=0;player.fuel=100;flight=false;player.velocity=0;camYaw=camPitch=0;tracked=null;scanUntil=0;resetControls();renderer.eye=[player.x,5,player.z+7];save();hud();cover();running=false;}
function chapterEnd(ch){$('#end-role').textContent='ЖИЗНЬ #'+ch+' · ЗАВЕРШЕНА';$('#end-title').textContent=ch===1?'Экипаж найден':ch===2?'Вместе — новый горизонт':'Чертёж ракеты спасён';$('#end-text').textContent=ch===1?'Связь восстановлена. Впереди встреча с командой, ремонт ранца и первая общая база.':ch===2?'Экипаж снова вместе, база построена. Инженер поймал новый сигнал заброшенной станции. Третья жизнь уже доступна.':'Ты расшифровал архив и передал чертёж инженеру. Три жизни пройдены. Продолжай исследовать мир и развивать базу; следующая глава — подготовка ракеты.';$('#end-next').textContent=ch<3?'Перейти к жизни #'+(ch+1):'Продолжить исследование';$('#end-next').onclick=()=>{$('#end').close();if(ch<3)enterNextLife();else toast('Чертёж сохранён в журнале экспедиции.');};openDialog('end');}
function journalText(){return ['clueValley','clueCrater','clueResearch'].filter(id=>state.signalClues.includes(id)).map(id=>Core.SIGNAL_NOTES[id]).join('\n\n');}
function showVault(){activePuzzle='vault';$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent='ОБСЕРВАТОРИЯ · АРХИВ';$('#puzzle-title').textContent='Код старой экспедиции';$('#puzzle-text').textContent='Введи три цифры в порядке записей I, II, III. Найденные записи приведены ниже.';const notes=document.createElement('p');notes.className='beacon-notes';notes.textContent=journalText();$('#puzzle-content').append(notes);const row=document.createElement('div');row.className='vault-code';for(let i=0;i<3;i++){const label=document.createElement('label');label.textContent=['I','II','III'][i];const input=document.createElement('input');input.type='number';input.inputMode='numeric';input.min='0';input.max='9';input.step='1';input.value='';input.setAttribute('aria-label','Цифра записи '+(i+1));label.append(input);row.append(label);}$('#puzzle-content').append(row);openDialog('puzzle');}
$('#next-life').onclick=()=>{$('#chapters').close();enterNextLife();};$('#journal-button').onclick=()=>{$('#signal-journal-notes').textContent=journalText()||'Записи ещё не найдены. Третья жизнь откроется после завершения второй.';$('#signal-journal-blueprint').textContent=state.blueprint?'Чертёж ракеты сохранён. '+(state.chapter3Complete?'Инженер получил чертёж.':'Передай его инженеру в лагере.'):'Чертёж пока не найден.';$('#chapters').close();openDialog('signal-journal');};$('#journal-close').onclick=()=>$('#signal-journal').close();
$('#build').onclick=()=>{if(state.chapter<2||!state.artifact){toast('Сначала найди архив с чертежами во второй жизни.');return;}showBuilder();};for(let b of document.querySelectorAll('[data-build]'))b.onclick=()=>{let r=Core.build(state,b.dataset.build,player);if(r.ok){const safe=renderer.safeSpawn(player.x,player.z,state);player.x=safe.x;player.z=safe.z;}result(r);$('#builder-feedback').textContent=r.text;refreshBuilder();};for(let b of document.querySelectorAll('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();
function toggleFly(){if(!state.engineerFixed){if(player.alt<.05)player.velocity=3.7;return;}if(!flight&&player.fuel<12){toast('Подожди на поверхности: ранец заряжается.');return;}flight=!flight;hud();}
$('#fly').onclick=toggleFly;$('#scan').onclick=()=>{scanUntil=time+7+Core.level(state,'scanner')*2;Core.markDaily(state,'scanner');const found=Core.scanContract(state,player,Core.scanRadius(state));save();hud();ui();toast(found?'Обнаружено объектов: '+found+'. Метки сохранены на компасе.':'Сканер: радиус '+Math.round(Core.scanRadius(state))+' м. Осмотри отмеченный район.');};

function pips(l){return [1,2,3].map(n=>`<i class="${n<=l?'on':''}"></i>`).join('')+`<span>${l?l+' / 3':'ЗАКРЫТО'}</span>`;}
function wallet(){return `◆ ${state.crystals}/${Core.capacity(state)} · ▣ ${state.metal}/${Core.capacity(state)} · ⚡ ${Math.floor(state.energy)}/${Core.energyCapacity(state)}`;}
function renderCards(){Core.syncCards(state);const count=Object.keys(state.cards).length;$('#collection-summary').textContent=`Открыто ${count} из 6 · Первый уровень — за задания. Ресурсы в долине восстанавливаются каждые 90 секунд.`;$('#collection-wallet').textContent=wallet();if(!$('#cards-grid').children.length){for(const[id,c]of Object.entries(Core.CARDS)){const b=document.createElement('button');b.id='equipment-'+id;b.onclick=()=>showCard(id);$('#cards-grid').append(b);}}
for(const[id,c]of Object.entries(Core.CARDS)){const l=Core.level(state,id),b=$('#equipment-'+id);b.className='equipment-card'+(l?'':' locked');b.setAttribute('aria-label',c.name+', '+(l?'уровень '+l:c.unlock));if(b.dataset.level===String(l))continue;b.dataset.level=String(l);b.innerHTML=`<span class="card-tag">${c.category.toUpperCase()} · ${String(c.chapter).padStart(2,'0')}</span><span class="art">${MoonCardArt(id)}</span><strong>${c.name}</strong><span class="effect">${l?Core.cardEffect(state,id):c.unlock}</span><span class="level-pips">${pips(l)}</span><span class="status">${l===3?'Полностью улучшено':l?'Открыть улучшение →':'Открывается в приключении'}</span>`;}
$('#combo-status').className='combo-panel'+(Core.combo(state)?' active':'');$('#combo-status').textContent=Core.combo(state)?'✓ Команда разведки: сканер + дрон + маршрут штурмана. Радиус сканера +20%.':'Команда разведки · Открой сканер и дрона, помоги штурману — получи +20% к радиусу сканера.';
const d=Core.daily(state);$('#daily-tasks').innerHTML=['scanner','backpack','jetpack'].map(id=>`<span class="${d.done.includes(id)?'done':''}">${d.done.includes(id)?'✓ ':'○ '}${{scanner:'Сканирование',backpack:'Сбор ресурсов',jetpack:'Полёт 5 сек'}[id]}</span>`).join('');$('#claim-daily').disabled=d.claimed||d.done.length<3;$('#claim-daily').textContent=d.claimed?'Награда получена':'Забрать 4 ◆ + 6 ▣';}
function refreshCard(){const id=selectedCard,c=Core.CARDS[id],l=Core.level(state,id);$('#card-art').innerHTML=MoonCardArt(id);$('#card-category').textContent=c.subtitle;$('#card-title').textContent=c.name;$('#card-level').innerHTML=pips(l);$('#card-current').textContent=l?Core.cardEffect(state,id):'Карточка ещё не открыта';$('#card-next').textContent=l&&l<3?'Следующий уровень: '+Core.cardEffect(state,id,l+1):l===3?'Оборудование улучшено до максимума.':'Первый уровень: '+Core.cardEffect(state,id,1);$('#card-condition').textContent=l?wallet():c.unlock+'. Первый уровень открывается бесплатно.';let cost=l&&l<3?c.costs[l-1]:null;$('#card-upgrade').hidden=!cost;$('#card-upgrade').disabled=!cost||state.crystals<cost[0]||state.metal<cost[1];$('#card-upgrade').textContent=cost?`Улучшить до ${l+1} · ${cost[0]} ◆ + ${cost[1]} ▣`:'';$('#card-track').textContent='Показать в мире';}
function showCard(id){selectedCard=id;$('#card-feedback').textContent='';refreshCard();openDialog('card-detail');}
$('#mission-toggle').onclick=()=>{const details=$('#detail'),button=$('#mission-toggle');details.hidden=!details.hidden;button.textContent=details.hidden?'+':'−';button.setAttribute('aria-expanded',String(!details.hidden));button.setAttribute('aria-label',details.hidden?'Развернуть подсказку':'Свернуть подсказку');};
$('#collection').onclick=()=>{Core.tick(state);renderCards();openDialog('cards');};
$('#card-upgrade').onclick=()=>{const r=Core.upgrade(state,selectedCard);$('#card-feedback').textContent=r.text;if(r.ok){save();hud();renderCards();refreshCard();}};
$('#card-track').onclick=()=>{const c=Core.CARDS[selectedCard];if(c.chapter>state.chapter){$('#card-feedback').textContent='Эта метка появится в жизни #'+c.chapter+'.';return;}let point=c.point;
if(selectedCard==='scanner'&&state.chapter>=2)point='navigator';
tracked={point,chapter:state.chapter,name:c.name};$('#card-detail').close();$('#cards').close();toast('Метка на компасе: '+c.name);};
$('#claim-daily').onclick=()=>{const r=Core.claimDaily(state);$('#daily-feedback').textContent=r.text;if(r.ok){save();hud();renderCards();}};
function refreshBuilder(){const names={habitat:'Жилой модуль',workshop:'Мастерская',solar:'Солнечная станция',beacon:'Маяк лагеря',dock:'Док дрона'};$('#base-energy').textContent=`⚡ ${Math.floor(state.energy)} / ${Core.energyCapacity(state)} · ${Core.energyRate(state)} энергии в час · ◆ ${state.crystals} · ▣ ${state.metal}`;
for(const b of document.querySelectorAll('[data-build]')){let id=b.dataset.build,built=state.buildings.includes(id),[c,m]=Core.COST[id],req={solar:1,beacon:2,dock:3}[id]||0,locked=Core.level(state,'workshop')<req;b.disabled=built||locked||state.crystals<c||state.metal<m;b.innerHTML=names[id]+` <span>${built?'✓ Построено':locked?'Мастерская '+req:c+' ◆ + '+m+' ▣'}</span>`;}
$('#craft-crystals').disabled=Core.level(state,'workshop')<1||state.energy<3;$('#craft-metal').disabled=Core.level(state,'workshop')<2||state.energy<2;}
function showBuilder(){Core.tick(state);refreshBuilder();$('#builder-feedback').textContent='';openDialog('builder');}
for(const type of ['crystals','metal'])$('#craft-'+type).onclick=()=>{Core.tick(state);const r=Core.craft(state,type,player);$('#builder-feedback').textContent=r.text;if(r.ok){save();hud();}refreshBuilder();};

document.addEventListener('error',e=>{if(e.target?.tagName==='IMG'&&e.target.getAttribute('src')?.startsWith('assets/cards/'))e.target.hidden=true;},true);
const chapterNames=['Пробуждение','Экипаж','Тайна сигнала','Первый полёт','Лунная база','Глубины','Потерянная экспедиция','Врата','Новый горизонт'];$('#menu').onclick=()=>{$('#menu-close').textContent=running?'Продолжить игру':'На главный экран';$('#menu-home').hidden=!running;$('#chapter-list').innerHTML='';chapterNames.forEach((name,i)=>{let div=document.createElement('div');div.className='chapter-card'+(i>=3?' locked':'');let num=document.createElement('strong');num.textContent=String(i+1).padStart(2,'0');let title=document.createElement('div');title.textContent=name;let status=document.createElement('small');status.textContent=i>=3?'В разработке':i+1<state.chapter?'Пройдена':i+1===state.chapter?(i===1&&state.complete||i===2&&state.chapter3Complete?'Пройдена':'Текущая глава'):i===2&&state.complete?'Доступна · начать ниже':'Откроется после жизни #'+i;title.append(status);div.append(num,title);$('#chapter-list').append(div);});openDialog('chapters');};try{const quality=localStorage.getItem(Core.KEY+'-quality');if(['high','low'].includes(quality))renderer.quality=quality;}catch{}$('#quality').value=renderer.quality;$('#quality').onchange=e=>{renderer.quality=e.target.value;try{localStorage.setItem(Core.KEY+'-quality',renderer.quality);}catch{}};let restarting=false;$('#restart').onclick=()=>{if(!restarting){restarting=true;$('#restart').textContent='Удалить прогресс и начать жизнь #1? Нажми ещё раз';return;}const kept={streak:state.streak,growth:state.growth};state=Core.initial();if(kept.streak)state.streak=kept.streak;if(kept.growth){state.growth=kept.growth;state.growth.resetAt=Date.now();}player.x=state.x;player.z=state.z;player.alt=0;player.fuel=100;player.velocity=0;flight=false;camYaw=0;camPitch=0;renderer.eye=[0,5,20];restarting=false;tracked=null;flightSeconds=0;scanUntil=0;$('#restart').textContent='Начать заново…';$('#chapters').close();save();hud();running=false;cover();};$('#chapters').addEventListener('close',()=>{restarting=false;$('#restart').textContent='Начать заново…';});
$('#cover-menu').onclick=()=>$('#menu').onclick();
$('#cover-cards').onclick=()=>$('#collection').onclick();
$('#cover-map').onclick=()=>$('#world-map-button').onclick();
$('#cover-expeditions').onclick=()=>{$('#expeditions-feedback').textContent='';showExpeditions();};
$('#menu-cards').onclick=()=>{$('#chapters').close();$('#collection').onclick();};
$('#menu-map').onclick=()=>{$('#chapters').close();$('#world-map-button').onclick();};
$('#menu-home').onclick=()=>{save();resetControls();$('#chapters').close();running=false;cover();};
$('#benchmark-button').onclick=()=>{$('#chapters').close();$('#benchmark-output').value=window.MoonBench?.report()||'';openDialog('benchmark');};
$('#benchmark-start').onclick=()=>{window.MoonBench?.start();$('#benchmark').close();$('#begin').onclick();};
$('#benchmark-stop').onclick=()=>{if(window.MoonBench){window.MoonBench.active=false;window.MoonBench.persist();$('#benchmark-output').value=window.MoonBench.report();}};
let joyId=null,lookId=null,lookX=0,lookY=0;const joystick=$('#joystick');function joyMove(e){let b=joystick.getBoundingClientRect(),x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,max=b.width*.29,l=Math.hypot(x,y);if(l>max){x*=max/l;y*=max/l;}joy={x:x/max,y:y/max};$('#thumb').style.transform=`translate(${x}px,${y}px)`;}
joystick.onpointerdown=e=>{if(joyId!==null)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joyMove(e);};joystick.onpointermove=e=>{if(e.pointerId===joyId)joyMove(e);};function joyEnd(e){if(e.pointerId!==joyId)return;joyId=null;joy={x:0,y:0};$('#thumb').style.transform='';}joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=joyEnd;const canvas=$('#world');canvas.onpointerdown=e=>{if(lookId!==null||!running||document.querySelector('dialog[open]')||e.button>0)return;e.preventDefault?.();lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(e.pointerId!==lookId)return;e.preventDefault?.();camYaw=Math.atan2(Math.sin(camYaw-(e.clientX-lookX)*.005),Math.cos(camYaw-(e.clientX-lookX)*.005));camPitch=Math.max(-.25,Math.min(.65,camPitch+(e.clientY-lookY)*.004));lookX=e.clientX;lookY=e.clientY;};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=e=>{if(e.pointerId===lookId)lookId=null;};
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||!running)return;let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(!e.repeat&&k==='e')$('#interact').click();if(!e.repeat&&k===' ')toggleFly();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{resetControls();joyId=lookId=null;});document.addEventListener('visibilitychange',()=>{if(!document.hidden){Core.tick(state);hud();if($('#cards').open)renderCards();if($('#builder').open)refreshBuilder();}if(document.hidden){resetControls();save();}last=0;});window.addEventListener('pagehide',save);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();save();running=false;$('#error').hidden=false;$('#error').textContent='3D-рендеринг приостановлен устройством. Прогресс сохранён. Перезагрузи страницу, чтобы продолжить.';});
function canMove(x,z){return !renderer.blocked(x,z,state,player.alt);}

function ui(){let q=Core.quest(state);near=Core.nearestTarget(state,player);$('#detail').textContent=q.id==='cells'&&!state.cells.includes('cell1')&&Math.hypot(player.x-Core.POINTS.cell1[0],player.z)<8?'Низкое ограждение: нажми «Прыжок» и направь джойстик к энергоблоку.':q.detail;let dist=near?Math.hypot(player.x-near.x,player.z-near.z):Infinity;if(dist>3.3||player.alt>1.1)near=null;$('#interact').style.opacity=near?1:.55;$('#interact span').textContent=near?(near.type?'Собрать':near.id.startsWith('sample')?'Взять пробу':near.id.startsWith('salvage')&&near.id!=='salvageBase'?'Забрать груз':q.id==='engineer'||q.id==='navigator'||q.id==='scout'||q.id==='repair'?'Поговорить':'Активировать'):'Подойти к цели';let targets=q.targets.map(id=>({id,x:Core.POINTS[id][0],z:Core.POINTS[id][1]})).sort((a,b)=>Math.hypot(player.x-a.x,player.z-a.z)-Math.hypot(player.x-b.x,player.z-b.z));if(tracked&&tracked.chapter===state.chapter){const[x,z]=Core.POINTS[tracked.point];targets.unshift({id:tracked.point,x,z,tracked:true});if(Math.hypot(player.x-x,player.z-z)<3.5){toast('Метка найдена: '+tracked.name);tracked=null;}}let target=targets[0];$('#destination').hidden=!target;if(target){let a=Math.atan2(target.x-player.x,player.z-target.z);$('#direction').style.transform=`rotate(${a+camYaw}rad)`;$('#distance').textContent=Math.round(Math.hypot(player.x-target.x,player.z-target.z))+(target.tracked?(target.id.startsWith('region_')?' м до района':' м до карточки'):' м до цели');}$('#fuel-fill').style.width=player.fuel+'%';$('.fuel').style.opacity=state.engineerFixed?1:.3;$('#labels').innerHTML='';const hudBottom=($('#expedition-hud').getBoundingClientRect().bottom||190)+10;let range=scanUntil>time?Core.scanRadius(state):Core.droneRadius(state);const discoveries=Core.discoveries(state,player,range);let shown=0;const labelItems=new Map();for(const item of [...targets,...discoveries])labelItems.set(item.id,{...labelItems.get(item.id),...item});for(let item of [...labelItems.values()].sort((a,b)=>Math.hypot(player.x-a.x,player.z-a.z)-Math.hypot(player.x-b.x,player.z-b.z))){if(shown>=5)break;let d=Math.hypot(player.x-item.x,player.z-item.z);if(!item.label&&!item.tracked&&d>26&&scanUntil<time)continue;let projected=renderer.project(item.x,Core.height(item.x,item.z,state.chapter)+4.3,item.z);if(!projected||projected.x<0||projected.x>renderer.canvas.clientWidth||projected.y<hudBottom||projected.y>renderer.canvas.clientHeight-180)continue;let el=document.createElement('span');el.className='world-label';el.textContent=(item.label?item.label+' · ':'')+Math.round(d)+' м';el.style.left=projected.x+'px';el.style.top=projected.y+'px';$('#labels').append(el);shown++;}}
function frame(ms){let dt=Math.min(last?(ms-last)/1000:0,.045);last=ms;time+=dt;const paused=!running||document.hidden||!!document.querySelector('dialog[open]');if(!paused){let ix=joy.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),iz=joy.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(ix,iz);if(l>1){ix/=l;iz/=l;}let dx=ix*Math.cos(camYaw)+iz*Math.sin(camYaw),dz=-ix*Math.sin(camYaw)+iz*Math.cos(camYaw),speed=flight?6.5:3.7;const previousX=player.x,previousZ=player.z;player.speed=0;if(l>.08){let nx=Math.max(Core.WORLD.minX,Math.min(Core.WORLD.maxX,player.x+dx*dt*speed)),nz=Math.max(Core.WORLD.minZ,Math.min(Core.WORLD.maxZ,player.z+dz*dt*speed));if(canMove(nx,player.z))player.x=nx;if(canMove(player.x,nz))player.z=nz;let targetYaw=Math.atan2(-dx,-dz),difference=Math.atan2(Math.sin(targetYaw-player.yaw),Math.cos(targetYaw-player.yaw));player.yaw+=difference*Math.min(1,dt*10);}player.speed=dt>0?Math.min(1,Math.hypot(player.x-previousX,player.z-previousZ)/(dt*speed)):0;if(flight){let day=Core.daily(state).day;if(day!==flightDay){flightDay=day;flightSeconds=0;}flightSeconds+=dt;if(flightSeconds>=5)Core.markDaily(state,'jetpack');player.alt+=(3.2-player.alt)*Math.min(1,dt*4);player.fuel=Math.max(0,player.fuel-dt*Core.fuelDrain(state));if(player.fuel<=0){flight=false;toast('Энергия закончилась. Ранец выполняет посадку.');hud();}}else{if(player.velocity>0||player.alt>.02){player.velocity-=dt*5;player.alt=Math.max(0,player.alt+player.velocity*dt);if(player.alt===0)player.velocity=0;}if(player.alt<.1)player.fuel=Math.min(100,player.fuel+dt*10);} if(player.alt<.1&&!canMove(player.x,player.z)){const safe=renderer.safeSpawn(player.x,player.z,state);player.x=safe.x;player.z=safe.z;player.velocity=0;toast('Небезопасная посадка — возвращение на ближайший твёрдый грунт.');}const update=Core.advanceContract(state,player,dt);if(update){save();hud();ui();toast(update.text);}}else player.speed=0;
economyTime+=dt;if(economyTime>=1){economyTime=0;Core.tick(state);$('#hud-energy').textContent=Math.floor(state.energy);if($('#cards').open)renderCards();if($('#builder').open)refreshBuilder();}
renderTime+=dt;let rendered=false;if(!paused||!renderer.vp||renderTime>=.2){rendered=true;renderer.render(state,player,time,Math.min(.2,renderTime)||.016,camYaw,camPitch,scanUntil>time);renderTime=0;}uiTime+=dt;if(uiTime>.12){uiTime=0;ui();}if(window.MoonBench?.tick(ms,paused,player.speed,rendered))toast('10 минут движения записаны. Отчёт: Меню → Проверка плавности.');requestAnimationFrame(frame);}
setInterval(()=>{if(running)save();},4000);requestAnimationFrame(frame);

$('#world-map-button').onclick=()=>{const regions=[{id:'base',name:'Лагерь экипажа',x:0,z:-5},...Core.REGIONS];const content=$('#world-map-content');content.innerHTML=`<svg viewBox="-90 -92 180 176" role="img" aria-label="Карта: лагерь и три новых района"><path d="M-82 -84H82V76H-82Z" fill="#102b3b" stroke="#6a91a5" stroke-width=".7"/>${regions.map(r=>`<path d="M${player.x} ${player.z}L${r.x} ${r.z}" stroke="#29475b" stroke-width=".5"/><circle cx="${r.x}" cy="${r.z}" r="3" fill="#e9c67a"/><text x="${r.x}" y="${r.z-6}" text-anchor="middle" font-size="5" fill="#dfeef4">${r.name}</text>`).join('')}<circle cx="${player.x}" cy="${player.z}" r="3" fill="#55def0"/><circle cx="${player.x}" cy="${player.z}" r="5" fill="none" stroke="#55def0" stroke-width=".7"/></svg><p>Бирюзовая точка — ты. Север — вверх. Выбери район, чтобы включить компас.</p>`;for(const r of regions){const button=document.createElement('button');button.textContent=r.name+' · '+Math.round(Math.hypot(player.x-r.x,player.z-r.z))+' м';button.onclick=()=>{tracked={point:'region_'+r.id,name:r.name,chapter:state.chapter};Core.POINTS[tracked.point]=[r.x,r.z];$('#world-map').close();toast('Маршрут: '+r.name);};content.append(button);}openDialog('world-map');};$('#world-map-close').onclick=()=>$('#world-map').close();
// Narrow bridge for growth.js (streak, crew, share, cloud save). Game rules stay in core.js / growth-core.js.
window.MoonGame={get state(){return state;},save,hud,toast,openDialog,resetControls,get running(){return running;},onSave:null,
 replace(raw){const next=Core.sanitize(raw);if(next.version!==Core.SAVE_VERSION)return false;state=next;Core.tick(state);const p=renderer.safeSpawn(state.x,state.z,state);player.x=p.x;player.z=p.z;player.alt=0;player.velocity=0;tracked=null;savedBody='';save();hud();if(!running)cover();return true;},
 refresh(){hud();if($('#cards').open)renderCards();}};
})();
