(()=>{'use strict';const $=s=>document.querySelector(s),Core=MoonCore;let state=Core.initial();try{state=Core.sanitize(JSON.parse(localStorage.getItem(Core.KEY)));}catch{}Core.tick(state);let renderer;try{renderer=new MoonRenderer($('#world'));}catch(e){$('#error').hidden=false;$('#error').textContent=_t('game.udalos_zapustit')+' '+e.message;$('#cover').hidden=true;return;}
const spawn=renderer.safeSpawn(state.x,state.z,state);const player={x:spawn.x,z:spawn.z,alt:0,yaw:-Math.PI/2,speed:0,fuel:100,velocity:0};let camYaw=0,camPitch=0,flight=false,keys={},joy={x:0,y:0},time=0,last=0,running=false,scanUntil=0,near=null,saveBad=false,toastTimer,uiTime=0,activePuzzle=null,route=[],selectedCard=null,tracked=null,flightSeconds=0,flightDay=Core.daily(state).day,economyTime=0,renderTime=0;
const STORIES={recorder:[_t('game.bortovoy_zhurnal'),_t('game.posledniy_signal'),_t('game.kapsula_povrezhden')],engineer:[_t('game.engineer_inzhener'),_t('game.remont_nachinaetsy'),_t('game.rad_tebya')],repair:[_t('game.engineer_inzhener'),_t('game.ranets_vosstanovle'),_t('game.gotovo_knopka')],navigator:[_t('game.navigator_shturman'),_t('game.karta_treh'),_t('game.aktiviruy_tri')],scout:[_t('game.scout_razvedchik'),_t('game.sledy_staroy'),_t('game.dalnem_kanone')],artifact:[_t('game.arhiv_ekspeditsii'),_t('game.chertezhi_naydeny'),_t('game.arhive_sohranilis')]};
Object.assign(STORIES,{signalStart:[_t('game.zhizn_3'),_t('game.stantsiya_otvechae'),_t('game.yuzhnaya_observato')],blueprint:[_t('game.arhiv_stantsii'),_t('game.chertezh_rakety'),_t('game.arhive_nayden')]});
// v43 LIFE #4 · THE ROCKET
Object.assign(STORIES,{rocketPlan:[_t('ch4.s_plan_role'),_t('ch4.s_plan_title'),_t('ch4.s_plan')],wreck:[_t('ch4.s_wreck_role'),_t('ch4.s_wreck_title'),_t('ch4.s_wreck')],engineIn:[_t('ch4.s_pad_role'),_t('ch4.s_engine_title'),_t('ch4.s_engine')],
 cave:[_t('ch4.s_cave_role'),_t('ch4.s_cave_title'),_t('ch4.s_cave')],coreIn:[_t('ch4.s_pad_role'),_t('ch4.s_core_title'),_t('ch4.s_core')],hangar:[_t('ch4.s_hangar_role'),_t('ch4.s_hangar_title'),_t('ch4.s_hangar')],rocketReady:[_t('ch4.s_pad_role'),_t('ch4.s_ready_title'),_t('ch4.s_ready')]});
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.opacity=0,2900);}
let savedBody='';function save(){state.x=player.x;state.z=player.z;const stamp=state.updatedAt;state.updatedAt=0;const body=JSON.stringify(state);state.updatedAt=body===savedBody&&stamp?stamp:Date.now();savedBody=body;window.MoonGame?.onSave?.(state);try{localStorage.setItem(Core.KEY,JSON.stringify(state));$('#save').textContent=_t('game.progress_sohranen');saveBad=false;}catch{if(!saveBad)toast(_t('game.brauzer_razreshaet'));saveBad=true;$('#save').textContent=_t('game.sohranenie_nedostu');}}
function resetControls(){const stick=$('#joystick'),world=$('#world');if(joyId!==null&&stick.hasPointerCapture?.(joyId))stick.releasePointerCapture(joyId);if(lookId!==null&&world.hasPointerCapture?.(lookId))world.releasePointerCapture(lookId);joyId=lookId=null;joy={x:0,y:0};keys={};$('#thumb').style.transform='';}
function openDialog(id){resetControls();$('#'+id).showModal();}
function hud(){Core.syncCards(state);let q=Core.quest(state);$('#card-count').textContent=Object.keys(state.cards).length+'/6';$('#crystals').textContent=state.crystals;$('#metal').textContent=state.metal;$('#hud-energy').textContent=Math.floor(state.energy);$('#chapter-title').textContent=q.contract?_t('game.polevaya_ekspedits'):_t('life.title',{n:state.chapter,name:_t('chapter.'+state.chapter)}).toLocaleUpperCase(MoonI18n.lang);$('#objective').textContent=q.title;$('#detail').textContent=q.detail;$('#progress-fill').style.width=(q.fraction*100)+'%';$('#fly span').textContent=state.engineerFixed?(flight?_t('game.posadka'):_t('game.ranets')):_t('game.pryzhok');$('#build').style.opacity=state.artifact?1:.5;const nextReady=state.chapter===2&&state.complete||state.chapter===3&&state.chapter3Complete;$('#next-life').hidden=!nextReady;if(nextReady)$('#next-life').textContent=_t('ch4.start_life',{life:_t('life.title',{n:state.chapter+1,name:_t('chapter.'+(state.chapter+1))})});}
function cover(){let ch=state.chapter;$('#cover').hidden=false;$('#cover-title').innerHTML=_t('life.n',{n:ch})+'<br>'+_t('chapter.'+Math.min(4,Math.max(1,ch)));$('#cover-text').textContent=ch===4?_t('ch4.cover_text'):ch===3?_t('game.observatoriya_snov'):ch===1?_t('game.posle_avariynoy'):_t('game.ty_nashel');$('.cover-art').style.backgroundImage=`linear-gradient(180deg,#081e2c00 20%,#07192770 55%,#071927ff 90%),url('${ch===4?'assets/world-cover-chapter4-v43.jpg':`assets/world-cover-chapter${ch}-v29.png`}')`;$('#begin').innerHTML=(state.recorder||state.chapter>=2?_t('game.prodolzhit_ekspedi'):_t('game.nachat_ekspeditsiy'))+' <span>→</span>';}
$('#begin').onclick=()=>{running=true;$('#cover').hidden=true;toast(_t('game.levyy_dzhoystik'));hud();};cover();hud();

function showExpeditions(){
 const list=$('#expeditions-list');list.innerHTML='';
 for(const[id,c]of Object.entries(Core.CONTRACTS)){
  const progress=state.expeditions.progress[id],row=document.createElement('article');row.className='contract-card';row.dataset.contract=id;
  const type=document.createElement('small');type.textContent=c.region+' · '+c.type;
  const title=document.createElement('h3');title.textContent=c.name;
  const description=document.createElement('p');description.textContent=c.detail;
  const status=document.createElement('p');status.className='contract-status';status.textContent=Core.contractStatus(state,id)+(progress.best===null?'':' · '+_t('game.rekord',{sec:progress.best.toFixed(1)}));
  const reward=document.createElement('span');reward.className='contract-reward';reward.textContent=c.reward[0]+' ◆ + '+c.reward[1]+' ▣';
  const action=document.createElement('button');action.id='contract-'+id;action.className='primary';action.disabled=!c.ready(state)||progress.done&&progress.claimed&&id!=='flight';
  const claim=progress.done&&!progress.claimed;action.textContent=claim?_t('game.zabrat_nagradu'):state.expeditions.active===id?_t('game.prodolzhit'):progress.done&&id==='flight'?_t('game.povtorit_marshrut'):_t('game.nachat_ekspeditsiy');
  action.onclick=()=>{if(claim){const r=Core.claimContract(state,id);$('#expeditions-feedback').textContent=r.text;if(r.ok){save();hud();showExpeditions();}return;}const r=state.expeditions.active===id?{ok:true,text:_t('game.prodolzhaem_eksped')}:Core.beginContract(state,id);if(r.ok){tracked=null;$('#expeditions').close();result(r);}else $('#expeditions-feedback').textContent=r.text;};
  row.append(type,title,description,status,reward,action);list.append(row);
 }
 $('#expeditions-wallet').textContent=wallet();if(!$('#expeditions').open)openDialog('expeditions');
}
$('#expeditions-button').onclick=()=>{$('#chapters').close();$('#expeditions-feedback').textContent='';showExpeditions();};
$('#map-expeditions').onclick=()=>{$('#world-map').close();$('#expeditions-feedback').textContent='';showExpeditions();};
$('#expeditions-close').onclick=()=>$('#expeditions').close();
$('#resume-story').onclick=()=>{$('#expeditions').close();result(Core.suspendContract(state));};
function showRelay(){
 activePuzzle='relay';route=state.expeditions.progress.relay.rotations.slice();$('#puzzle-content').innerHTML='';$('#puzzle-feedback').textContent='';$('#puzzle-role').textContent=_t('game.observatoriya_pita');$('#puzzle-title').textContent=_t('game.vosstanovi_silovuy');$('#puzzle-text').textContent=_t('game.nazhimay_segmenty');
 const grid=document.createElement('div');grid.className='relay-grid';const buttons=[];
 const update=()=>{const trace=Core.relayTrace(route);buttons.forEach((b,i)=>{const ports=Core.relayPorts(i,route[i]),ends=[[32,4],[60,32],[32,60],[4,32]];b.innerHTML='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="'+ports.map(n=>'M32 32L'+ends[n][0]+' '+ends[n][1]).join('')+'"/></svg><span>'+String(i+1)+'</span>';b.dataset.powered=String(trace.powered.includes(i));b.setAttribute('aria-label',_t('game.segment',{n:i+1,deg:route[i]*90})+', '+(trace.powered.includes(i)?_t('game.pod_napryazheniem'):_t('game.bez_pitaniya')));});state.expeditions.progress.relay.rotations=route.slice();$('#puzzle-feedback').textContent=trace.connected?_t('game.liniya_soedinena'):_t('game.poverni_segmenty');save();};
 for(let i=0;i<6;i++){const b=document.createElement('button');b.id='relay-tile-'+i;b.onclick=()=>{route[i]=(route[i]+1)%4;update();};buttons.push(b);grid.append(b);}
 $('#puzzle-content').append(grid);update();openDialog('puzzle');
}

$('#story-close').onclick=()=>$('#story').close();function story(id){const[role,title,text]=STORIES[id];$('#story-role').textContent=role;$('#story-title').textContent=title;$('#story-text').textContent=text;openDialog('story');}
function result(r){if(!r.ok){toast(r.text);return;}let fresh=Core.syncCards(state);save();hud();ui();if(fresh.length)toast(_t('game.otkryty_kartochki')+' '+fresh.map(id=>Core.CARDS[id].name).join(', '));if(r.text)toast(r.text);if(r.story)story(r.story);if(r.puzzle)showPuzzle(r.puzzle);if(r.builder)showBuilder();if(r.contractDone)showExpeditions();if(r.chapterEnd)chapterEnd(r.chapterEnd);if(r.nextLife)enterNextLife();window.MoonGame?.onResult?.(r);}
$('#interact').onclick=()=>{if(!near){toast(_t('game.podoydi_predmetu'));return;}result(Core.interact(state,near.id,player));};
function showPuzzle(type){if(type==='relay'){showRelay();return;}if(type==='vault'){showVault();return;}if(type==='power'){showPower();return;}if(type==='align'){showAlign();return;}activePuzzle=type;route=[];$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent=type==='signal'?_t('game.antenna_kalibrovka'):_t('game.navigator_marshrut');$('#puzzle-title').textContent=type==='signal'?_t('game.poymay_signal'):_t('game.tri_mayaka');$('#puzzle-text').textContent=type==='signal'?_t('game.medlenno_menyay'):_t('game.soedini_mayaki');if(type==='signal'){[32,68,45].forEach((target,i)=>{let row=document.createElement('div');row.className='slider-row';let label=document.createElement('label');label.textContent=_t('game.kanal',{n:i+1})+' ';let output=document.createElement('b');output.textContent='0';label.append(output);let input=document.createElement('input');input.type='range';input.min='0';input.max='100';input.value='0';input.setAttribute('aria-label',_t('game.chastota_kanala',{n:i+1}));let meter=document.createElement('div');meter.className='signal-meter';let fill=document.createElement('i');meter.append(fill);const tune=()=>{const strength=Core.signalStrength(i,input.value);output.textContent=_t('game.otklik',{n:strength});fill.style.width=strength+'%';meter.dataset.locked=strength>=79?'true':'false';};input.oninput=tune;tune();row.append(label,input,meter);$('#puzzle-content').append(row);});}else{let notes=document.createElement('p');notes.className='beacon-notes';notes.textContent=['beacon3','beacon1','beacon2'].filter(id=>state.beacons.includes(id)).map(id=>Core.BEACON_NOTES[id]).join('\n');$('#puzzle-content').append(notes);let choices=document.createElement('div');choices.className='route-buttons';for(let [id,title]of[['white',_t('game.belyy')],['cyan',_t('game.biryuzovyy')],['gold',_t('game.zolotoy')]]){let b=document.createElement('button');b.dataset.node=id;b.textContent=title;b.onclick=()=>{if(route.length===3)route=[];route.push(id);$('#route-result').textContent=route.map(v=>({cyan:'◆',gold:'●',white:'◇'})[v]).join(' → ');};choices.append(b);}let output=document.createElement('p');output.id='route-result';$('#puzzle-content').append(choices,output);}openDialog('puzzle');}
$('#puzzle-submit').onclick=()=>{let value=activePuzzle==='power'?state.powerGrid.slice():activePuzzle==='align'?state.alignRings.slice():activePuzzle==='vault'?[...$('#puzzle-content').querySelectorAll('input')].map(e=>e.value.trim()===''?NaN:Number(e.value)):activePuzzle==='signal'?[...$('#puzzle-content').querySelectorAll('input')].map(e=>Number(e.value)):route;let r=Core.solve(state,activePuzzle,value);if(r.ok){$('#puzzle').close();result(r);}else{$('#puzzle-feedback').textContent=r.text;if(activePuzzle==='route'){route=[];$('#route-result').textContent='';}}};$('#puzzle-close').onclick=()=>$('#puzzle').close();
function enterNextLife(){if(!Core.nextChapter(state))return;Core.suspendContract(state);const safe=renderer.safeSpawn(state.x,state.z,state);player.x=safe.x;player.z=safe.z;player.alt=0;player.fuel=100;flight=false;player.velocity=0;camYaw=camPitch=0;tracked=null;scanUntil=0;resetControls();renderer.eye=[player.x,5,player.z+7];save();hud();cover();running=false;}
function chapterEnd(ch){$('#end-role').textContent=_t('game.zavershena',{n:ch});$('#end-title').textContent=ch===1?_t('game.ekipazh_nayden'):ch===2?_t('game.vmeste_novyy'):ch===3?_t('game.chertezh_rakety2'):_t('ch4.end_title');$('#end-text').textContent=ch===1?_t('game.svyaz_vosstanovlen'):ch===2?_t('game.ekipazh_snova'):ch===3?_t('game.ty_rasshifroval'):_t('ch4.end_text');$('#end-next').textContent=ch<4?_t('game.pereyti_zhizni',{n:ch+1}):_t('game.prodolzhit_issledo');$('#end').classList?.toggle('cliffhanger',ch===4);
 $('#end-next').onclick=()=>{$('#end').close();if(ch<4)enterNextLife();else toast(_t('ch4.end_toast'));};
 // LIFE #4 ends on a cliffhanger: the «engines silent» card plays first, then the end dialog.
 if(ch===4&&window.MoonCinema&&window.MoonCinema.play('ch4end',{onEnd:()=>openDialog('end')}))return;openDialog('end');}
// v43 puzzles. Power: turn cable tiles until power runs from the generator (left) to the cargo winch (right).
function showPower(){activePuzzle='power';$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent=_t('ch4.power_role');$('#puzzle-title').textContent=_t('ch4.power_title');$('#puzzle-text').textContent=_t('ch4.power_text');
 const wrap=document.createElement('div');wrap.className='power-wrap';const src=document.createElement('span');src.className='power-end src';src.textContent='⚡';const dst=document.createElement('span');dst.className='power-end dst';dst.textContent='⚙';
 const grid=document.createElement('div');grid.className='relay-grid power-grid';const buttons=[];const ends=[[32,4],[60,32],[32,60],[4,32]];
 const update=()=>{const trace=Core.powerTrace(state.powerGrid);buttons.forEach((b,i)=>{const ports=Core.powerPorts(i,state.powerGrid[i]);b.innerHTML='<svg viewBox="0 0 64 64" aria-hidden="true"><path d="'+ports.map(n=>'M32 32L'+ends[n][0]+' '+ends[n][1]).join('')+'"/></svg>';b.dataset.powered=String(trace.powered.includes(i));b.setAttribute('aria-label',_t('ch4.power_tile',{n:i+1,deg:state.powerGrid[i]*90})+', '+(trace.powered.includes(i)?_t('game.pod_napryazheniem'):_t('game.bez_pitaniya')));});wrap.dataset.connected=String(trace.connected);$('#puzzle-feedback').textContent=trace.connected?_t('ch4.power_ready'):_t('ch4.power_hint');save();};
 for(let i=0;i<9;i++){const b=document.createElement('button');b.type='button';b.id='power-tile-'+i;b.onclick=()=>{state.powerGrid[i]=(state.powerGrid[i]+1)%4;update();};buttons.push(b);grid.append(b);}
 wrap.append(src,grid,dst);$('#puzzle-content').append(wrap);update();openDialog('puzzle');}
// Align: three rings of the upper stage. Each ring also turns the one below it.
function showAlign(){activePuzzle='align';$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent=_t('ch4.align_role');$('#puzzle-title').textContent=_t('ch4.align_title');$('#puzzle-text').textContent=_t('ch4.align_text');
 const list=document.createElement('div');list.className='align-rings';const rows=[];const names=[_t('ch4.ring_nose'),_t('ch4.ring_collar'),_t('ch4.ring_fins')];
 const update=()=>{rows.forEach((row,i)=>{const v=state.alignRings[i];row.mark.style.transform=`rotate(${v*45}deg)`;row.el.dataset.aligned=String(v===0);row.state.textContent=v===0?'✓':(v*45)+'°';row.btn.setAttribute('aria-label',names[i]+' · '+(v*45)+'°');});const all=state.alignRings.every(v=>v===0);$('#puzzle-feedback').textContent=all?_t('ch4.align_ready'):_t('ch4.align_hint');save();};
 names.forEach((name,i)=>{const el=document.createElement('div');el.className='align-row';const dial=document.createElement('span');dial.className='align-dial';dial.innerHTML='<svg viewBox="0 0 40 40" aria-hidden="true"><circle cx="20" cy="20" r="15"/><path d="M20 2v6"/></svg>';const mark=document.createElement('i');dial.append(mark);const label=document.createElement('b');label.textContent=name;const st=document.createElement('small');const btn=document.createElement('button');btn.type='button';btn.id='align-ring-'+i;btn.textContent=_t('ch4.ring_turn');btn.onclick=()=>{state.alignRings=Core.alignTurn(state.alignRings,i);update();};el.append(dial,label,st,btn);list.append(el);rows.push({el,mark,state:st,btn});});
 $('#puzzle-content').append(list);update();openDialog('puzzle');}
function journalText(){return ['clueValley','clueCrater','clueResearch'].filter(id=>state.signalClues.includes(id)).map(id=>Core.SIGNAL_NOTES[id]).join('\n\n');}
function showVault(){activePuzzle='vault';$('#puzzle-feedback').textContent='';$('#puzzle-content').innerHTML='';$('#puzzle-role').textContent=_t('game.observatoriya_arhi');$('#puzzle-title').textContent=_t('game.kod_staroy');$('#puzzle-text').textContent=_t('game.vvedi_tri');const notes=document.createElement('p');notes.className='beacon-notes';notes.textContent=journalText();$('#puzzle-content').append(notes);const row=document.createElement('div');row.className='vault-code';for(let i=0;i<3;i++){const label=document.createElement('label');label.textContent=['I','II','III'][i];const input=document.createElement('input');input.type='number';input.inputMode='numeric';input.min='0';input.max='9';input.step='1';input.value='';input.setAttribute('aria-label',_t('game.tsifra_zapisi',{n:i+1}));label.append(input);row.append(label);}$('#puzzle-content').append(row);openDialog('puzzle');}
$('#next-life').onclick=()=>{$('#chapters').close();enterNextLife();};$('#journal-button').onclick=()=>{$('#signal-journal-notes').textContent=journalText()||_t('game.zapisi_esche');$('#signal-journal-blueprint').textContent=state.blueprint?_t('game.chertezh_rakety3')+' '+(state.chapter3Complete?_t('game.inzhener_poluchil'):_t('game.pereday_ego')):_t('game.chertezh_poka');$('#chapters').close();openDialog('signal-journal');};$('#journal-close').onclick=()=>$('#signal-journal').close();
$('#build').onclick=()=>{if(state.chapter<2||!state.artifact){toast(_t('game.snachala_naydi'));return;}showBuilder();};for(let b of document.querySelectorAll('[data-build]'))b.onclick=()=>{let r=Core.build(state,b.dataset.build,player);if(r.ok){const safe=renderer.safeSpawn(player.x,player.z,state);player.x=safe.x;player.z=safe.z;}result(r);$('#builder-feedback').textContent=r.text;refreshBuilder();};for(let b of document.querySelectorAll('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();
function toggleFly(){if(!state.engineerFixed){if(player.alt<.05)player.velocity=3.7;return;}if(!flight&&player.fuel<12){toast(_t('game.podozhdi_poverhnos'));return;}flight=!flight;hud();}
$('#fly').onclick=toggleFly;$('#scan').onclick=()=>{scanUntil=time+7+Core.level(state,'scanner')*2;Core.markDaily(state,'scanner');const found=Core.scanContract(state,player,Core.scanRadius(state));save();hud();ui();toast(found?_t('game.obnaruzheno_obekto',{n:found}):_t('game.skaner_radius',{m:Math.round(Core.scanRadius(state))}));};

function pips(l){return [1,2,3].map(n=>`<i class="${n<=l?'on':''}"></i>`).join('')+`<span>${l?l+' / 3':_t('game.zakryto')}</span>`;}
function wallet(){return `◆ ${state.crystals}/${Core.capacity(state)} · ▣ ${state.metal}/${Core.capacity(state)} · ⚡ ${Math.floor(state.energy)}/${Core.energyCapacity(state)}`;}
function renderCards(){Core.syncCards(state);const count=Object.keys(state.cards).length;$('#collection-summary').textContent=`${_t('game.otkryto_6',{count:count})}`;$('#collection-wallet').textContent=wallet();if(!$('#cards-grid').children.length){for(const[id,c]of Object.entries(Core.CARDS)){const b=document.createElement('button');b.id='equipment-'+id;b.onclick=()=>showCard(id);$('#cards-grid').append(b);}}
for(const[id,c]of Object.entries(Core.CARDS)){const l=Core.level(state,id),b=$('#equipment-'+id);b.className='equipment-card'+(l?'':' locked');b.setAttribute('aria-label',c.name+', '+(l?_t('game.uroven',{n:l}):c.unlock));if(b.dataset.level===String(l))continue;b.dataset.level=String(l);b.innerHTML=`<span class="card-tag">${c.category.toUpperCase()} · ${String(c.chapter).padStart(2,'0')}</span><span class="art">${MoonCardArt(id)}</span><strong>${c.name}</strong><span class="effect">${l?Core.cardEffect(state,id):c.unlock}</span><span class="level-pips">${pips(l)}</span><span class="status">${l===3?_t('game.polnostyu_uluchshe'):l?_t('game.otkryt_uluchshenie'):_t('game.otkryvaetsya_prikl')}</span>`;}
$('#combo-status').className='combo-panel'+(Core.combo(state)?' active':'');$('#combo-status').textContent=Core.combo(state)?_t('game.komanda_razvedki'):_t('game.komanda_razvedki2');
const d=Core.daily(state);$('#daily-tasks').innerHTML=['scanner','backpack','jetpack'].map(id=>`<span class="${d.done.includes(id)?'done':''}">${d.done.includes(id)?'✓ ':'○ '}${{scanner:_t('game.skanirovanie'),backpack:_t('game.sbor_resursov'),jetpack:_t('game.polet_5')}[id]}</span>`).join('');$('#claim-daily').disabled=d.claimed||d.done.length<3;$('#claim-daily').textContent=d.claimed?_t('exp.nagrada_poluchena'):_t('game.zabrat_4');}
function refreshCard(){const id=selectedCard,c=Core.CARDS[id],l=Core.level(state,id);$('#card-art').innerHTML=MoonCardArt(id);$('#card-category').textContent=c.subtitle;$('#card-title').textContent=c.name;$('#card-level').innerHTML=pips(l);$('#card-current').textContent=l?Core.cardEffect(state,id):_t('game.kartochka_esche');$('#card-next').textContent=l&&l<3?_t('game.sleduyuschiy_urove')+' '+Core.cardEffect(state,id,l+1):l===3?_t('game.oborudovanie_uluch'):_t('game.pervyy_uroven')+' '+Core.cardEffect(state,id,1);$('#card-condition').textContent=l?wallet():_t('game.pervyy_uroven2',{task:c.unlock});let cost=l&&l<3?c.costs[l-1]:null;$('#card-upgrade').hidden=!cost;$('#card-upgrade').disabled=!cost||state.crystals<cost[0]||state.metal<cost[1];$('#card-upgrade').textContent=cost?`${_t('game.uluchshit',{v:l+1,cost:cost[0],cost2:cost[1]})}`:'';$('#card-track').textContent=_t('game.pokazat_mire');}
function showCard(id){selectedCard=id;$('#card-feedback').textContent='';refreshCard();openDialog('card-detail');}
$('#mission-toggle').onclick=()=>{const details=$('#detail'),button=$('#mission-toggle');details.hidden=!details.hidden;button.textContent=details.hidden?'+':'−';button.setAttribute('aria-expanded',String(!details.hidden));button.setAttribute('aria-label',details.hidden?_t('game.razvernut_podskazk'):_t('game.svernut_podskazku'));};
$('#collection').onclick=()=>{Core.tick(state);renderCards();openDialog('cards');};
$('#card-upgrade').onclick=()=>{const r=Core.upgrade(state,selectedCard);$('#card-feedback').textContent=r.text;if(r.ok){save();hud();renderCards();refreshCard();}};
$('#card-track').onclick=()=>{const c=Core.CARDS[selectedCard];if(c.chapter>state.chapter){$('#card-feedback').textContent=_t('game.eta_metka',{n:c.chapter});return;}let point=c.point;
if(selectedCard==='scanner'&&state.chapter>=2)point='navigator';
tracked={point,chapter:state.chapter,name:c.name};$('#card-detail').close();$('#cards').close();toast(_t('game.metka_kompase')+' '+c.name);};
$('#claim-daily').onclick=()=>{const r=Core.claimDaily(state);$('#daily-feedback').textContent=r.text;if(r.ok){save();hud();renderCards();}};
function refreshBuilder(){const names={habitat:_t('game.zhiloy_modul'),workshop:_t('core.masterskaya'),solar:_t('core.solnechnaya_stants'),beacon:_t('game.mayak_lagerya'),dock:_t('game.dok_drona')};$('#base-energy').textContent=`${_t('game.energii_chas',{energy:Math.floor(state.energy),energyCapacity:Core.energyCapacity(state),energyRate:Core.energyRate(state),crystals:state.crystals,metal:state.metal})}`;
for(const b of document.querySelectorAll('[data-build]')){let id=b.dataset.build,built=state.buildings.includes(id),[c,m]=Core.COST[id],req={solar:1,beacon:2,dock:3}[id]||0,locked=Core.level(state,'workshop')<req;b.disabled=built||locked||state.crystals<c||state.metal<m;b.innerHTML=names[id]+` <span>${built?_t('game.postroeno'):locked?_t('game.masterskaya',{n:req}):c+' ◆ + '+m+' ▣'}</span>`;}
$('#craft-crystals').disabled=Core.level(state,'workshop')<1||state.energy<3;$('#craft-metal').disabled=Core.level(state,'workshop')<2||state.energy<2;}
function showBuilder(){Core.tick(state);refreshBuilder();$('#builder-feedback').textContent='';openDialog('builder');}
for(const type of ['crystals','metal'])$('#craft-'+type).onclick=()=>{Core.tick(state);const r=Core.craft(state,type,player);$('#builder-feedback').textContent=r.text;if(r.ok){save();hud();}refreshBuilder();};

document.addEventListener('error',e=>{if(e.target?.tagName==='IMG'&&e.target.getAttribute('src')?.startsWith('assets/cards/'))e.target.hidden=true;},true);
const chapterNames=[1,2,3,4,5,6,7,8,9].map(n=>_t('chapter.'+n));$('#menu').onclick=()=>{$('#menu-close').textContent=running?_t('game.prodolzhit_igru'):_t('game.glavnyy_ekran');$('#menu-home').hidden=!running;$('#chapter-list').innerHTML='';const READY=4,done=[state.chapter>1,state.complete,state.chapter3Complete,state.chapter4Complete];chapterNames.forEach((name,i)=>{let div=document.createElement('div');div.className='chapter-card'+(i>=READY?' locked':'');let num=document.createElement('strong');num.textContent=String(i+1).padStart(2,'0');let title=document.createElement('div');title.textContent=name;let status=document.createElement('small');status.textContent=i>=READY?(i===READY?_t('ch4.next_update'):_t('game.razrabotke')):i+1<state.chapter?_t('game.proydena'):i+1===state.chapter?(done[i]?_t('game.proydena'):_t('game.tekuschaya_glava')):i+1===state.chapter+1&&done[i-1]?_t('game.dostupna_nachat'):_t('game.otkroetsya_posle',{n:i});title.append(status);div.append(num,title);$('#chapter-list').append(div);});openDialog('chapters');};try{const quality=localStorage.getItem(Core.KEY+'-quality');if(['high','low'].includes(quality))renderer.quality=quality;}catch{}$('#quality').value=renderer.quality;$('#quality').onchange=e=>{renderer.quality=e.target.value;try{localStorage.setItem(Core.KEY+'-quality',renderer.quality);}catch{}};let restarting=false;$('#restart').onclick=()=>{if(!restarting){restarting=true;$('#restart').textContent=_t('game.udalit_progress');return;}const kept={streak:state.streak,growth:state.growth,cinema:state.cinema,team:state.team};state=Core.initial();if(kept.streak)state.streak=kept.streak;if(kept.cinema)state.cinema=kept.cinema;if(kept.team)state.team=kept.team;if(kept.growth){state.growth=kept.growth;state.growth.resetAt=Date.now();}player.x=state.x;player.z=state.z;player.alt=0;player.fuel=100;player.velocity=0;flight=false;camYaw=0;camPitch=0;renderer.eye=[0,5,20];restarting=false;tracked=null;flightSeconds=0;scanUntil=0;$('#restart').textContent=_t('game.nachat_zanovo');$('#chapters').close();save();hud();running=false;cover();};$('#chapters').addEventListener('close',()=>{restarting=false;$('#restart').textContent=_t('game.nachat_zanovo');});
$('#cover-menu').onclick=()=>$('#menu').onclick();
$('#cover-cards').onclick=()=>$('#collection').onclick();
$('#cover-map').onclick=()=>$('#world-map-button').onclick();
$('#cover-expeditions').onclick=()=>{$('#expeditions-feedback').textContent='';showExpeditions();};
$('#menu-cards').onclick=()=>{$('#chapters').close();$('#collection').onclick();};
$('#menu-map').onclick=()=>{$('#chapters').close();$('#world-map-button').onclick();};
$('#menu-home').onclick=()=>{save();resetControls();$('#chapters').close();running=false;cover();};
$('#benchmark-button').onclick=()=>{$('#chapters').close();$('#benchmark-output').value=window.MoonBench?.report()||'';openDialog('benchmark');};
$('#benchmark-start').onclick=()=>{window.MoonBench?.start();$('#benchmark').close();$('#begin').onclick();};
$('#benchmark-stop').onclick=()=>{if(window.MoonBench){window.MoonBench.active=false;window.MoonBench.persist();$('#benchmark-output').value=window.MoonBench.report();}};
let joyId=null,lookId=null,lookX=0,lookY=0;const joystick=$('#joystick');function joyMove(e){let b=joystick.getBoundingClientRect(),x=e.clientX-b.left-b.width/2,y=e.clientY-b.top-b.height/2,max=b.width*.29,l=Math.hypot(x,y);if(l>max){x*=max/l;y*=max/l;}joy={x:x/max,y:y/max};$('#thumb').style.transform=`translate(${x}px,${y}px)`;}
joystick.onpointerdown=e=>{if(joyId!==null)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joyMove(e);};joystick.onpointermove=e=>{if(e.pointerId===joyId)joyMove(e);};function joyEnd(e){if(e.pointerId!==joyId)return;joyId=null;joy={x:0,y:0};$('#thumb').style.transform='';}joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=joyEnd;const canvas=$('#world');canvas.onpointerdown=e=>{if(lookId!==null||!running||document.querySelector('dialog[open]')||e.button>0)return;e.preventDefault?.();lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(e.pointerId!==lookId)return;e.preventDefault?.();camYaw=Math.atan2(Math.sin(camYaw-(e.clientX-lookX)*.005),Math.cos(camYaw-(e.clientX-lookX)*.005));camPitch=Math.max(-.25,Math.min(.65,camPitch+(e.clientY-lookY)*.004));lookX=e.clientX;lookY=e.clientY;};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=e=>{if(e.pointerId===lookId)lookId=null;};
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||!running)return;let k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys[k]=true;if(!e.repeat&&k==='e')$('#interact').click();if(!e.repeat&&k===' ')toggleFly();});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{resetControls();joyId=lookId=null;});document.addEventListener('visibilitychange',()=>{if(!document.hidden){Core.tick(state);hud();if($('#cards').open)renderCards();if($('#builder').open)refreshBuilder();}if(document.hidden){resetControls();save();}last=0;});window.addEventListener('pagehide',save);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();save();running=false;$('#error').hidden=false;$('#error').textContent=_t('game.3d_rendering');});
function canMove(x,z){return !renderer.blocked(x,z,state,player.alt);}

function ui(){let q=Core.quest(state);near=Core.nearestTarget(state,player);$('#detail').textContent=q.id==='cells'&&!state.cells.includes('cell1')&&Math.hypot(player.x-Core.POINTS.cell1[0],player.z)<8?_t('game.nizkoe_ograzhdenie'):q.detail;let dist=near?Math.hypot(player.x-near.x,player.z-near.z):Infinity;if(dist>3.3||player.alt>1.1)near=null;$('#interact').style.opacity=near?1:.55;$('#interact span').textContent=near?(near.type?_t('game.sobrat'):near.id.startsWith('sample')?_t('game.vzyat_probu'):near.id.startsWith('salvage')&&near.id!=='salvageBase'?_t('game.zabrat_gruz'):q.id==='engineer'||q.id==='navigator'||q.id==='scout'||q.id==='repair'||q.id==='padBrief'||q.id==='wreck'||q.id==='hangar'||q.id==='complete3'?_t('game.pogovorit'):q.id==='shards'||q.id==='parts'?_t('ch4.btn_take'):q.id==='engineDeliver'||q.id==='coreDeliver'?_t('ch4.btn_install'):q.id==='ignition'?_t('ch4.btn_ignite'):_t('game.aktivirovat')):_t('game.podoyti_tseli');let targets=q.targets.map(id=>({id,x:Core.POINTS[id][0],z:Core.POINTS[id][1]})).sort((a,b)=>Math.hypot(player.x-a.x,player.z-a.z)-Math.hypot(player.x-b.x,player.z-b.z));if(tracked&&tracked.chapter===state.chapter){const[x,z]=Core.POINTS[tracked.point];targets.unshift({id:tracked.point,x,z,tracked:true});if(Math.hypot(player.x-x,player.z-z)<3.5){toast(_t('game.metka_naydena')+' '+tracked.name);tracked=null;}}let target=targets[0];$('#destination').hidden=!target;if(target){let a=Math.atan2(target.x-player.x,player.z-target.z);$('#direction').style.transform=`rotate(${a+camYaw}rad)`;$('#distance').textContent=_t(target.tracked?(target.id.startsWith('region_')?'game.m_rayona':'game.m_kartochki'):'game.m_tseli',{m:Math.round(Math.hypot(player.x-target.x,player.z-target.z))});}$('#fuel-fill').style.width=player.fuel+'%';$('.fuel').style.opacity=state.engineerFixed?1:.3;$('#labels').innerHTML='';const hudBottom=($('#expedition-hud').getBoundingClientRect().bottom||190)+10;let range=scanUntil>time?Core.scanRadius(state):Core.droneRadius(state);const discoveries=Core.discoveries(state,player,range);let shown=0;const labelItems=new Map();for(const item of [...targets,...discoveries])labelItems.set(item.id,{...labelItems.get(item.id),...item});for(let item of [...labelItems.values()].sort((a,b)=>Math.hypot(player.x-a.x,player.z-a.z)-Math.hypot(player.x-b.x,player.z-b.z))){if(shown>=5)break;let d=Math.hypot(player.x-item.x,player.z-item.z);if(!item.label&&!item.tracked&&d>26&&scanUntil<time)continue;let projected=renderer.project(item.x,Core.height(item.x,item.z,state.chapter)+4.3,item.z);if(!projected||projected.x<0||projected.x>renderer.canvas.clientWidth||projected.y<hudBottom||projected.y>renderer.canvas.clientHeight-180)continue;let el=document.createElement('span');el.className='world-label';el.textContent=(item.label?item.label+' · ':'')+_t('game.m',{m:Math.round(d)});el.style.left=projected.x+'px';el.style.top=projected.y+'px';$('#labels').append(el);shown++;}}
function frame(ms){let dt=Math.min(last?(ms-last)/1000:0,.045);last=ms;time+=dt;const paused=!running||document.hidden||!!document.querySelector('dialog[open]');if(!paused){let ix=joy.x+(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),iz=joy.y+(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),l=Math.hypot(ix,iz);if(l>1){ix/=l;iz/=l;}let dx=ix*Math.cos(camYaw)+iz*Math.sin(camYaw),dz=-ix*Math.sin(camYaw)+iz*Math.cos(camYaw),speed=flight?6.5:3.7;const previousX=player.x,previousZ=player.z;player.speed=0;if(l>.08){let nx=Math.max(Core.WORLD.minX,Math.min(Core.WORLD.maxX,player.x+dx*dt*speed)),nz=Math.max(Core.WORLD.minZ,Math.min(Core.WORLD.maxZ,player.z+dz*dt*speed));if(canMove(nx,player.z))player.x=nx;if(canMove(player.x,nz))player.z=nz;let targetYaw=Math.atan2(-dx,-dz),difference=Math.atan2(Math.sin(targetYaw-player.yaw),Math.cos(targetYaw-player.yaw));player.yaw+=difference*Math.min(1,dt*10);}player.speed=dt>0?Math.min(1,Math.hypot(player.x-previousX,player.z-previousZ)/(dt*speed)):0;if(flight){let day=Core.daily(state).day;if(day!==flightDay){flightDay=day;flightSeconds=0;}flightSeconds+=dt;if(flightSeconds>=5)Core.markDaily(state,'jetpack');player.alt+=(3.2-player.alt)*Math.min(1,dt*4);player.fuel=Math.max(0,player.fuel-dt*Core.fuelDrain(state));if(player.fuel<=0){flight=false;toast(_t('game.energiya_zakonchil'));hud();}}else{if(player.velocity>0||player.alt>.02){player.velocity-=dt*5;player.alt=Math.max(0,player.alt+player.velocity*dt);if(player.alt===0)player.velocity=0;}if(player.alt<.1)player.fuel=Math.min(100,player.fuel+dt*10);} if(player.alt<.1&&!canMove(player.x,player.z)){const safe=renderer.safeSpawn(player.x,player.z,state);player.x=safe.x;player.z=safe.z;player.velocity=0;toast(_t('game.nebezopasnaya_posa'));}const update=Core.advanceContract(state,player,dt);if(update){save();hud();ui();toast(update.text);}}else player.speed=0;
economyTime+=dt;if(economyTime>=1){economyTime=0;Core.tick(state);$('#hud-energy').textContent=Math.floor(state.energy);if($('#cards').open)renderCards();if($('#builder').open)refreshBuilder();}
renderTime+=dt;let rendered=false;if((!paused||!renderer.vp||renderTime>=.2)&&!window.MoonCinema?.playing){rendered=true;renderer.render(state,player,time,Math.min(.2,renderTime)||.016,camYaw,camPitch,scanUntil>time);renderTime=0;}uiTime+=dt;if(uiTime>.12){uiTime=0;ui();}if(window.MoonBench?.tick(ms,paused,player.speed,rendered))toast(_t('game.10_minut'));requestAnimationFrame(frame);}
setInterval(()=>{if(running)save();},4000);requestAnimationFrame(frame);

$('#world-map-button').onclick=()=>{const regions=[{id:'base',name:_t('game.lager_ekipazha'),x:0,z:-5},...Core.REGIONS,...(state.chapter===4?Core.REGIONS4:[])];const content=$('#world-map-content');content.innerHTML=`<svg viewBox="-90 -92 180 176" role="img" aria-label="${_t('game.karta_lager')}"><path d="M-82 -84H82V76H-82Z" fill="#102b3b" stroke="#6a91a5" stroke-width=".7"/>${regions.map(r=>`<path d="M${player.x} ${player.z}L${r.x} ${r.z}" stroke="#29475b" stroke-width=".5"/><circle cx="${r.x}" cy="${r.z}" r="3" fill="#e9c67a"/><text x="${r.x}" y="${r.z-6}" text-anchor="middle" font-size="5" fill="#dfeef4">${r.name}</text>`).join('')}<circle cx="${player.x}" cy="${player.z}" r="3" fill="#55def0"/><circle cx="${player.x}" cy="${player.z}" r="5" fill="none" stroke="#55def0" stroke-width=".7"/></svg><p>${_t('game.biryuzovaya_tochka')}</p>`;for(const r of regions){const button=document.createElement('button');button.textContent=r.name+' · '+_t('game.m',{m:Math.round(Math.hypot(player.x-r.x,player.z-r.z))});button.onclick=()=>{tracked={point:'region_'+r.id,name:r.name,chapter:state.chapter};Core.POINTS[tracked.point]=[r.x,r.z];$('#world-map').close();toast(_t('game.marshrut')+' '+r.name);};content.append(button);}openDialog('world-map');};$('#world-map-close').onclick=()=>$('#world-map').close();
// Narrow bridge for growth.js (streak, crew, share, cloud save). Game rules stay in core.js / growth-core.js.
window.MoonGame={get state(){return state;},save,hud,toast,openDialog,resetControls,get running(){return running;},onSave:null,onResult:null,
 replace(raw){const next=Core.sanitize(raw);if(next.version!==Core.SAVE_VERSION)return false;state=next;Core.tick(state);const p=renderer.safeSpawn(state.x,state.z,state);player.x=p.x;player.z=p.z;player.alt=0;player.velocity=0;tracked=null;savedBody='';save();hud();if(!running)cover();return true;},
 refresh(){hud();if($('#cards').open)renderCards();}};
})();
